import Foundation

// MARK: - قاموس الترجمة الإنجليزية
//
// المفتاح = النص العربي كما هو مكتوب في الكود بالضبط (بما فيه علامات الترقيم
// والمسافات). القيمة = الترجمة الإنجليزية الاحترافية. أي مفتاح مفقود هنا يسقط
// للعربية تلقائيًا (`L(...)`), فالإضافة تدريجية وآمنة.
//
// عند تحويل شاشة جديدة لـ `L(...)`: أضِف كل نصوصها هنا. حافظ على الترتيب
// حسب الشاشة كي تسهل المراجعة. القوالب (%d / %@) تُترجَم عبر `Lf(...)` وتحتفظ
// بنفس المحدّدات وترتيبها.
nonisolated enum SpEnglishStrings {
    static let map: [String: String] = [
        // ── التبويبات (RootTabView) ──
        "المباريات": "Matches",
        "روشن": "Roshn",
        "البطولات": "Competitions",
        "عالمية": "World",
        "حسابي": "Account",

        // ── شاشات الترحيب (Onboarding) ──
        "تخطّي": "Skip",
        "التالي": "Next",
        "ابدأ الآن": "Get Started",
        "مرحبًا بك في VARA": "Welcome to VARA",
        "دقّة الرياضة في راحة يدك — مباريات، بطولات، وتوقّعات ذكية في تطبيق واحد.":
            "Sports precision in the palm of your hand — matches, competitions, and smart predictions in one app.",
        "أحد منتجات": "A product of",
        "صحيفة سبق": "Sabq",
        "كل المباريات في مكان واحد": "All matches in one place",
        "جدول موحّد لكل البطولات، ومركز مباراة غنيّ بالأحداث والإحصائيات والتشكيلات والتقييمات.":
            "A unified schedule for every competition, plus a rich match center with events, stats, lineups, and ratings.",
        "توقّع VARA الذكي": "Smart VARA Predictions",
        "خوارزمية ديناميكية تحسب احتمالات النتيجة من الترتيب والفورمة وأفضلية الأرض — ونافس على لوحة المتصدّرين.":
            "A dynamic algorithm computes outcome odds from standings, form, and home advantage — then compete on the leaderboard.",
        "تابع فريقك ولا تفوّت لحظة": "Follow your team, never miss a moment",
        "تنبيهات فورية للأهداف والبطاقات وحالات الفار، وبطاقة «مبارياتي» بعدّاد تنازليّ حيّ.":
            "Instant alerts for goals, cards, and VAR reviews, plus a “My Matches” card with a live countdown.",

        // ── المظهر واللغة (AccountView) ──
        "المظهر": "Appearance",
        "«تلقائي» يتبع إعداد جهازك؛ أو اختر الفاتح/الداكن يدويًّا.":
            "“Automatic” follows your device setting; or choose light/dark manually.",
        "لون التطبيق": "App Color",
        "اختر لونك المفضل للأزرار والأيقونات والترويسات؛ البطولات تبقى بنفس قالب التطبيق.":
            "Pick your favorite color for buttons, icons, and headers; competitions keep the same app template.",
        "تلقائي": "Automatic",
        "فاتح": "Light",
        "داكن": "Dark",
        "اللغة": "Language",
        "اختر لغة الواجهة. قد تبقى بيانات المباريات بالعربية حتى تدعمها البوابة بالإنجليزية.":
            "Choose the interface language. Match data may stay in Arabic until the gateway supports English.",

        // ── مركز المباريات (MatchesCenterView) ──
        "اليوم": "Today",
        "دخول": "Sign In",
        "تسجيل الدخول بعضوية سبق": "Sign in with your Sabq membership",
        "اختيار البطولات": "Choose competitions",
        "اختيار التاريخ": "Choose date",
        "مباشر": "Live",
        "عدسة": "Lens",
        "الكل": "All",
        "الأهم": "Top",
        "السعودية": "Saudi",
        "أوروبا": "Europe",
        "العالمية": "World",
        "عدسة العرض": "View lens",
        "تعذّر التحميل": "Couldn’t load",
        "اختر بطولاتك": "Choose your competitions",
        "فعّل البطولات التي تهمّك من أيقونة الضبط أعلى الشاشة ليظهر جدولها الموحّد هنا":
            "Enable the competitions you care about from the settings icon at the top to see their unified schedule here",
        "لا مباريات مباشرة الآن": "No live matches right now",
        "لا مباريات في هذه الفترة": "No matches in this period",
        "أوقف فلتر «مباشر» لعرض الجدول كاملًا": "Turn off the “Live” filter to see the full schedule",
        "جرّب بطولة أخرى أو عد لاحقًا": "Try another competition or check back later",
        "الأدوار الإقصائية": "Knockout Rounds",
        "مباريات اليوم": "Today’s Matches",
        "الأقرب": "Nearest",
        "غدًا": "Tomorrow",
        "أمس": "Yesterday",
        "جارية الآن": "Live now",
        "تنطلق قريبًا": "Starting soon",
        "انتهت": "Ended",
        "ما تفعّله هنا يظهر جدوله في «الكل» وفي بلوك «بطولاتي» بتبويب البطولات — مصدر واحد للمفضّلة.":
            "What you enable here shows up in “All” and in the “My Competitions” block on the Competitions tab — one source for favorites.",
        "بطولات الجدول": "Schedule Competitions",
        "تم": "Done",
        "اذهب إلى تاريخ": "Go to Date",
        "اذهب": "Go",
        "إلغاء": "Cancel",
        "تعذّر الاتصال بخادم البيانات": "Couldn’t reach the data server",
        "إلغاء متابعة المباراة": "Unfollow match",
        "متابعة المباراة": "Follow match",

        // ── الرئيسية / روشن (HomeView) ──
        "بحث": "Search",
        "لك": "For You",
        "الموسم سينطلق قريبًا": "Season starts soon",
        "فريقي المفضّل": "My Team",
        "دوري روشن": "Roshn League",
        "انتهت بالتعادل": "Ended in a draw",
        "%@ حسمها بفارق %d": "%@ sealed it by %d",
        "%@ انتصر بفارق %d": "%@ won by %d",
        "قادمة": "Upcoming",
        "استحواذ": "Possession",
        "تسديدات": "Shots",
        "ترتيب دوري روشن": "Roshn League Standings",
        "هدّافو دوري روشن": "Roshn League Scorers",
        "نبض %@": "%@ Pulse",
        "نبض الدوري": "League Pulse",
        "المركز %d": "Position %d",
        "صدارة مشتعلة": "Tight at the top",
        "الفارق %d نقطة": "%d-point lead",
        "%d نقطة": "%d pts",
        "%d فوز": "%d wins",
        "هدف": "goals",
        "صناعة": "assists",
        "%d هدف": "%d goals",
        "%d عليه": "%d against",
        "متساويان": "Level",
        "على الوصيف": "vs 2nd",
        "المركز": "Position",
        "لعب": "Played",
        "سجّل": "Scored",
        "استقبل": "Conceded",
        "هداف الفريق": "Team Scorer",
        "المتصدّر": "Leader",
        "الهدّاف": "Top Scorer",
        "أقوى هجوم": "Best Attack",
        "أمنع دفاع": "Best Defense",
        "فارق الصدارة": "Lead Gap",
        "جولة هذا الأسبوع": "This Week’s Round",
        "ترتيب %@": "%@ Standings",
        "سباق اللقب": "Title Race",
        "الترتيب الكامل": "Full table",
        " نقطة": " pts",
        "المتصدر": "Leader",
        "متساوٍ": "Level",
        "هدّافو %@": "%@ Scorers",
        "الهدّافون": "Top Scorers",
        "صنّاع %@": "%@ Assists",
        "صنّاع الأهداف": "Top Assists",
        "هدّافون": "Scorers",
        "صنّاع": "Assists",
        "آخر نتائج %@": "%@ Latest Results",
        "آخر النتائج": "Latest Results",
        "مركز الانتقالات": "Transfer Center",
        "المركز الكامل": "Full center",
        "إعارة": "Loan",
        "انتقال حر": "Free transfer",
        "لا يتوفّر ترتيب": "No standings available",
        "قد يكون الموسم لم يبدأ بعد": "The season may not have started yet",
        "النادي": "Club",
        "نقاط": "Pts",
        "أبطال آسيا": "AFC Champions",
        "الهبوط": "Relegation",
        "لا تتوفّر بيانات": "No data available",
        "لا نتائج": "No results",
        "لا أخبار حاليًا": "No news right now",
        "جرّب كلمة بحث أخرى": "Try another search term",
        "الأخبار الرياضية": "Sports News",
        "ابحث في الأخبار": "Search news",

        // ── مركز المباراة (MatchCenterView) ──
        "تقديم": "Preview",
        "الأحداث": "Events",
        "التعليق": "Commentary",
        "التحليل": "Analysis",
        "التقييمات": "Ratings",
        "التشكيلة": "Lineup",
        "الإحصاءات": "Stats",
        "المواجهات": "H2H",
        "مباراة عبر VARA": "Match via VARA",
        " (ترجيح %d-%d)": " (pens %d-%d)",
        "عبر VARA": "via VARA",
        "مركز المباراة": "Match Center",
        "فاز %@ بركلات الترجيح": "%@ won on penalties",
        "ركلات الترجيح": "Penalty Shootout",
        "الوقت المتبقّي على المباراة": "Time until kickoff",
        "اليوم والتاريخ": "Day & Date",
        "التوقيت": "Kickoff Time",
        "الملعب": "Stadium",
        "البطولة": "Competition",
        "الدور": "Round",
        "حكم المباراة": "Referee",
        "%d مباراة بالبطولة": "%d matches in the competition",
        "🟨 %d صفراء": "🟨 %d yellow",
        "🟥 %d حمراء": "🟥 %d red",
        "⚽ %d ركلة جزاء": "⚽ %d penalties",
        "فار ×%d": "VAR ×%d",
        "توقّع VARA": "VARA Prediction",
        "الأرجح %d-%d": "Most likely %d-%d",
        "تعادل": "Draw",
        "رؤية VARA": "VARA Insight",
        "الفورمة الأخيرة": "Recent Form",
        "ف": "W",
        "ت": "D",
        "خ": "L",
        "هدّافو الفريقين": "Top Scorers",
        "أهداف الموسم": "Season Goals",
        "أجواء المباراة": "Match Atmosphere",
        "الطقس": "Weather",
        "القنوات الناقلة": "Broadcasters",
        "رطوبة": "Humidity",
        "توقّع النتيجة": "Predict the Score",
        "توقّعك": "Your Prediction",
        "٣ نقاط للمطابقة": "3 pts for an exact score",
        "احفظ توقّعي": "Save Prediction",
        "تعديل التوقّع": "Edit Prediction",
        "يمكنك التعديل حتى انطلاق المباراة": "You can edit until kickoff",
        "تعذّر حفظ التوقّع": "Couldn’t save prediction",
        "لا تفاصيل بعد": "No details yet",
        "ستظهر الأحداث والإحصاءات والتشكيلة فور توفّرها": "Events, stats, and lineups will appear as soon as they’re available",
        "خطّ زمن المباراة": "Match Timeline",
        "أعلى": "Top",
        "أسفل": "Bottom",
        "نتيجة الشوط الأول": "Half-Time Score",
        "بديلًا عن: %@": "On for: %@",
        "صناعة: %@": "Assist: %@",
        "التعليق يتحدّث مباشرةً": "Commentary updates live",
        "تشكيلة متوقعة": "Predicted Lineup",
        "ترشيح المزوّد قبل الإعلان الرسمي — قد تتغيّر": "Provider’s pick before the official announcement — may change",
        "المدرب: %@": "Coach: %@",
        "دكة البدلاء": "Substitutes",
        "الأهداف المتوقّعة (xG)": "Expected Goals (xG)",
        "على المرمى (xGOT)": "On Target (xGOT)",
        "الزخم": "Momentum",
        "مؤشّر الضغط": "Pressure Index",
        "وقائع المباراة": "Match Facts",
        "الغيابات": "Absences",
        "المضيف": "Home",
        "الضيف": "Away",
        "أفضل لاعب في المباراة": "Player of the Match",
        "آخر %d لقاءات بين الفريقين": "Last %d meetings",

        // ── دفعة الترجمة الآلية (workflow) ──
        "· دقّة الرياضة": "· Sports precision",
        "تسجيل الخروج": "Sign Out",
        "سيتم إنهاء جلستك على هذا الجهاز. يبقى فريقك المفضّل ومبارياتك المتابَعة كما هي.": "This will end your session on this device. Your favorite team and followed matches will stay the same.",
        "عضو VARA": "VARA Member",
        "عضو سبق": "Sabq Member",
        "إدارة حساب سبق": "Manage Sabq Account",
        "تعديل الملف الشخصي": "Edit Profile",
        "الاسم الأول": "First name",
        "اسم العائلة": "Last name",
        "أدخل الاسم الأول": "Enter first name",
        "أدخل اسم العائلة": "Enter last name",
        "رقم الجوال": "Mobile number",
        "البريد الإلكتروني": "Email",
        "أضف بريدك الإلكتروني (اختياري)": "Add your email (optional)",
        "البريد اختياري — رقم الجوال هو وسيلة الدخول الأساسية": "Email is optional — your mobile number is the primary sign-in method",
        "لا يمكن تعديل الاسم بعد تعيينه لاعتبارات أمنية ومصداقية التعليقات": "Name can’t be changed after it’s set, for security and comment integrity",
        "حفظ التغييرات": "Save changes",
        "تم حفظ التغييرات بنجاح": "Changes saved successfully",
        "تعذّر حفظ الملف الشخصي": "Couldn’t save profile",
        "لا توجد تغييرات للحفظ": "Nothing to save",
        "صيغة البريد الإلكتروني غير صحيحة": "Invalid email format",
        "تعذّر رفع الصورة": "Couldn’t upload photo",
        "تعذّر قراءة الصورة": "Couldn’t read the photo",
        "تعذّر تجهيز الصورة": "Couldn’t prepare the photo",
        "تم تحديث الصورة الشخصية": "Profile photo updated",
        "الصورة تظهر في حسابك على سبق وVARA": "This photo appears on your Sabq and VARA account",
        "أضف اسمك ليظهر في عضويتك على سبق وVARA": "Add your name so it appears on your Sabq and VARA membership",
        "أكمل اسمك": "Complete your name",
        "حسابك بلا اسم — أضفه ليظهر في عضويتك": "Your account has no name — add it to show on your membership",
        "الأخبار الرياضية متوفرة بالعربية حاليًا": "Sports news is currently available in Arabic only",
        "رابط غير صالح": "Invalid URL",
        "استجابة غير صالحة من الخادم": "Invalid server response",
        "انتهت جلستك، يرجى تسجيل الدخول": "Your session expired, please sign in",
        "ليس لديك صلاحية": "You don’t have permission",
        "غير موجود": "Not found",
        "طلبات كثيرة، حاول لاحقًا": "Too many requests, try again later",
        "تعذّر قراءة البيانات": "Couldn’t read the data",
        "خطأ في الخادم (%d)": "Server error (%d)",
        "مشجّع %@": "Fan of %@",
        "تتابع %d فريقًا": "Following %d teams",
        "أهلًا بك في VARA": "Welcome to VARA",
        "التوقّعات": "Predictions",
        "توقّعات VARA": "VARA Predictions",
        "توقّع نتائج كأس العالم والبطولات وتنافس على النقاط والجوائز": "Predict World Cup and tournament results and compete for points and prizes",
        "فِرقي": "My Teams",
        "الفريق المفضّل يعمل بلا تسجيل دخول ويتصدّر صفحتك الرئيسية. سجّل الدخول لمتابعة عدّة فِرق وتلقّي تنبيهاتها.": "The favorite team works without signing in and tops your home page. Sign in to follow multiple teams and get their alerts.",
        "الفريق المفضّل": "Favorite Team",
        "اختره من نجمة صفحة أي نادٍ": "Pick it from the star on any club’s page",
        "إزالة الفريق المفضّل": "Remove favorite team",
        "الفِرق المتابَعة": "Followed Teams",
        "تنبيهات المباريات": "Match Alerts",
        "الإشعارات": "Notifications",
        "إدارة الإشعارات": "Manage Notifications",
        "تصلك إشعارات الفِرق المتابَعة والمباريات في «مبارياتي».": "You’ll get alerts for followed teams and matches in My Matches.",
        "إذن النظام · مبارياتي · تسجيل الدخول للتنبيهات اللحظية": "System permission · My Matches · Sign in for live alerts",
        "%d فِرق · %d مباريات · أنواع الأحداث": "%d teams · %d matches · event types",
        "كيف تصلك الإشعارات؟": "How do alerts reach you?",
        "تصلك إشعارات مباريات الفِرق التي تتابعها، والمباريات في «مبارياتي». فعّل أنواع الأحداث أدناه، وتأكد أن إذن النظام مسموح.": "You’ll get alerts for teams you follow and matches in My Matches. Enable event types below, and make sure system permission is allowed.",
        "الفريق المفضّل يخصّص واجهتك فقط ولا يفعّل الإشعارات بمفرده.": "Your favorite team only personalizes the UI and does not enable alerts by itself.",
        "إذن النظام": "System Permission",
        "إشعارات الجهاز": "Device Notifications",
        "تفعيل": "Enable",
        "فتح الإعدادات": "Open Settings",
        "بدون إذن النظام لن تصل الإشعارات حتى لو كانت المفاتيح مفعّلة داخل التطبيق.": "Without system permission, alerts won’t arrive even if in-app toggles are on.",
        "مسموح": "Allowed",
        "مرفوض — افتح إعدادات الجهاز": "Denied — open device settings",
        "لم يُطلب بعد": "Not requested yet",
        "غير معروف": "Unknown",
        "من أين تصلك؟": "Where do they come from?",
        "أضف فريقًا من صفحة النادي («تابع التنبيهات»)، أو أضف مباراة بنجمة ⭐ في جدول المباريات.": "Add a team from a club page (Follow Alerts), or star ⭐ a match in the fixtures list.",
        "يتطلّب تسجيل الدخول": "Requires sign-in",
        "لا فِرق بعد": "No teams yet",
        "إشعارات كل مباريات هذه الفِرق": "Alerts for all matches of these teams",
        "سجّل الدخول لمتابعة فِرق وتلقّي تنبيهاتها على كل أجهزتك.": "Sign in to follow teams and get their alerts on all your devices.",
        "لا فِرق متابَعة بعد — افتح صفحة نادٍ واضغط «تابع التنبيهات».": "No followed teams yet — open a club page and tap Follow Alerts.",
        "لا مباريات بعد": "No matches yet",
        "إشعارات هذه المباريات فقط + تذكير قبل 10 دقائق": "Alerts for these matches only + a reminder 10 minutes before",
        "لا مباريات في «مبارياتي» — اضغط النجمة ⭐ على أي مباراة في الجدول.": "No matches in My Matches — tap the star ⭐ on any fixture.",
        "و%d مباريات أخرى في الرئيسية": "and %d more matches on Home",
        "أحداث المباراة": "Match Events",
        "هذه المفاتيح عامّة: تنطبق على كل فِرقك المتابَعة وكل مبارياتك في «مبارياتي».": "These toggles are global: they apply to all followed teams and all matches in My Matches.",
        "تفعيل التنبيهات": "Enable Alerts",
        "سجّل الدخول لتفعيل التنبيهات": "Sign in to enable alerts",
        "تذكير «مبارياتي» المحلي يعمل بلا دخول. الإشعارات اللحظية (أهداف وبطاقات) تحتاج عضوية سبق.": "My Matches local reminders work without signing in. Live alerts (goals, cards) need a Sabq membership.",
        "عرض البطاقات داخل الشاشات — منفصل عن إشعار الدفع.": "Show cards inside screens — separate from push alerts.",
        "بداية المباراة": "Match start",
        "الأهداف": "Goals",
        "البطاقات": "Cards",
        "حالات الفار (VAR)": "VAR Reviews",
        "نهاية المباراة": "Match end",
        "لقطات ذكية": "Smart Snaps",
        "تابع فريقًا ليصلك تنبيه عند أحداث مبارياته.": "Follow a team to get alerts for its match events.",
        "تصلك هذه التنبيهات عن مباريات فِرقك المتابَعة.": "You’ll get these alerts for your followed teams’ matches.",
        "سجّل الدخول بعضوية سبق لتفعيل تنبيهات فِرقك": "Sign in with your Sabq membership to enable your teams’ alerts",
        "تنبيهات الانتقالات": "Transfer Alerts",
        "انتقالات سعودية": "Saudi Transfers",
        "انتقالات عالمية بارزة": "Notable Global Transfers",
        "تصلك الصفقات المؤكّدة فور تأكيدها — تنبيهات سوق عامّة لا تتطلّب متابعة فريق.": "You’ll get confirmed deals as soon as they’re confirmed — general market alerts that don’t require following a team.",
        "سجّل الدخول بعضوية سبق لتفعيل تنبيهات الانتقالات": "Sign in with your Sabq membership to enable transfer alerts",
        "مفعّل": "On",
        "متوقف": "Off",
        "عن التطبيق": "About the App",
        "سياسة الاستخدام": "Usage Policy",
        "شروط الاستخدام": "Terms of Use",
        "الدعم": "Support",
        "الإصدار": "Version",
        "إظهار اللقطات داخل التطبيق": "Show snaps within the app",
        "ظاهر": "Shown",
        "مخفي": "Hidden",
        "منطقة الخطر": "Danger Zone",
        "حذف الحساب": "Delete Account",
        "حذف الحساب يزيل ملفّك وبياناتك نهائيًّا ولا يمكن التراجع عنه.": "Deleting your account permanently removes your profile and data — this cannot be undone.",
        "مرحبًا بك في": "Welcome to",
        "سجّل بعضويتك في سبق لتحفظ فريقك، وترسل توقّعاتك، وتصلك تنبيهات المباريات على كل أجهزتك.": "Sign up with Sabq to save your team, submit your predictions, and get match alerts on all your devices.",
        "البريد الإلكتروني أو الجوال": "Email or mobile number",
        "كلمة المرور": "Password",
        "سبق": "Sabq",
        "الدخول بعضوية سبق": "Sign in with Sabq",
        // ── الدخول بالجوال + تبويبات العضوية (SpMembershipLogin / SpPhoneLoginFlow) ──
        "الجوال": "Phone",
        "عضوية سبق": "Sabq Membership",
        "سجّل دخولك لتحفظ فريقك، وترسل توقّعاتك، وتصلك تنبيهات المباريات على كل أجهزتك.": "Sign in to save your team, submit your predictions, and get match alerts on all your devices.",
        "سنرسل رمز تحقّق برسالة نصية إلى جوالك.": "We’ll send a verification code by SMS to your phone.",
        "أرسل رمز التحقق": "Send verification code",
        "أدخل رمز التحقق": "Enter verification code",
        "أُرسل إلى": "Sent to",
        "تعديل": "Edit",
        "إعادة إرسال الرمز": "Resend code",
        "تحقّق ودخول": "Verify & sign in",
        "إعادة الإرسال خلال %d ثانية": "Resend in %d s",
        "المتابعة عبر Apple": "Continue with Apple",
        "أو": "or",
        "تعذّر قراءة بيانات Apple": "Couldn’t read Apple data",
        "تعذّر تسجيل الدخول عبر Apple": "Couldn’t sign in with Apple",
        "أدخل البريد/الجوال وكلمة المرور": "Enter your email/phone and password",
        "بيانات الدخول غير صحيحة": "Incorrect login credentials",
        "البريد/الجوال أو كلمة المرور غير صحيحة": "Incorrect email/phone or password",
        "هذا الحساب غير مفعّل أو محظور": "This account is disabled or banned",
        "محاولات كثيرة، حاول بعد قليل": "Too many attempts, try again shortly",
        "تعذّر تسجيل الدخول": "Couldn’t sign in",
        "كلمة المرور غير صحيحة": "Incorrect password",
        "تعذّر حذف الحساب": "Couldn’t delete account",
        "تبدأ المباراة بعد ١٠ دقائق ⚽": "Match starts in 10 minutes ⚽",
        "هذا الشهر": "This month",
        "هذا الأسبوع": "This week",
        "لا متصدّرين بعد": "No leaders yet",
        "كن أول من يتصدّر بتوقّعاتك هذا الموسم": "Be the first to top the board with your predictions this season",
        "المجتمع": "Community",
        "لوحة المتصدّرين": "Leaderboard",
        "نافِس الجمهور بتوقّعاتك واصعد القمة": "Compete with the crowd and climb to the top",
        "سجّل الدخول من «حسابي» للمنافسة على لوحة المتصدّرين.": "Sign in from “Account” to compete on the leaderboard.",
        "ترتيبك": "Your Rank",
        "نقطة": "pts",
        "توقّع": "predictions",
        "صحيح": "correct",
        "لم تتوقّع بعد — ستظهر هنا بمجرد أول توقّع لك. (التوقّع قريبًا)": "You haven’t predicted yet — you’ll appear here once you make your first prediction. (Predictions coming soon)",
        "%d توقّع · %d صحيح · %d مطابق": "%d predictions · %d correct · %d exact",
        "كيف تُحتسب النقاط؟": "How are points calculated?",
        "نتيجة مطابقة تمامًا": "Exact score match",
        "٣ نقاط": "3 pts",
        "اتجاه صحيح (فوز/تعادل/خسارة)": "Correct outcome (win/draw/loss)",
        "نقطة واحدة": "1 pt",
        "توقّع خاطئ": "Wrong prediction",
        "٠": "0",
        "نظرة": "Overview",
        "الترتيب": "Standings",
        "الأدوار": "Rounds",
        "الصنّاع": "Assists",
        "الانتقالات": "Transfers",
        "كأس": "Cup",
        "دوري": "League",
        "الأدوار والمواعيد من جدول البطولة": "Rounds and dates from the competition schedule",
        "الترتيب والمباريات من الاشتراكات المتاحة": "Standings and matches from available feeds",
        "%d ناديًا": "%d clubs",
        "%d منتخبًا": "%d nations",
        "منتهٍ": "Finished",
        "جارٍ": "Ongoing",
        "قادم": "Upcoming",
        "مباشر الآن": "Live now",
        "النتائج": "Results",
        "كل المجموعات": "All groups",
        "أرقام اللاعبين": "Player Stats",
        "الهداف": "Top Scorer",
        "صانع اللعب": "Playmaker",
        "بطاقة": "cards",
        "كل المباريات": "All matches",
        "بطل موسم %@": "%@ season champion",
        "بطل الموسم": "Season champion",
        "الموسم": "Season",
        "النوع": "Type",
        "الأندية": "Clubs",
        "ملخص البطولة": "Competition Summary",
        "فريق مشارك": "Participating team",
        "فريق": "Team",
        "نتائج": "Results",
        "أقرب موعد": "Nearest date",
        "متاح": "Available",
        "غير متاح": "Unavailable",
        "إشارات البطولة": "Competition Signals",
        "بيانات البطولة": "Competition Data",
        "ستظهر المباريات والأرقام من الاشتراكات فور توفرها": "Matches and numbers will appear from the feeds as soon as they’re available",
        "أقرب مباراة": "Next Match",
        "الأدوار القادمة": "Upcoming Rounds",
        "%d مباراة": "%d matches",
        "الدور القادم": "Next Round",
        "هدّاف البطولة": "Competition Top Scorer",
        "صانع البطولة": "Competition Playmaker",
        "لا تتوفر المجموعات": "No groups available",
        "ستظهر فور تحديث بيانات البطولة": "Will appear once competition data updates",
        "الأدوار لم تكتمل": "Rounds not complete yet",
        "تظهر شجرة خروج المغلوب عند توفر مبارياتها": "The knockout bracket appears once its matches are available",
        "لا تتوفر البطاقات": "No cards available",
        "ستظهر بعد بداية مباريات البطولة": "Will appear once the competition’s matches begin",
        "%d صفراء · %d حمراء": "%d yellow · %d red",
        "لا يتوفّر هدّافون": "No scorers available",
        "ستظهر القائمة بعد بداية البطولة": "The list will appear once the competition begins",
        "%d مباراة · %d صناعة": "%d matches · %d assists",
        "لا يتوفّر صنّاع": "No assists available",
        "ستظهر القائمة بعد تسجيل أول صناعة": "The list will appear once the first assist is recorded",
        "%d مباراة · %d هدف": "%d matches · %d goals",
        "لا مباريات": "No matches",
        "لا توجد مباريات متاحة حاليًا لهذه البطولة": "No matches are currently available for this competition",
        "تعذّر جلب المباريات": "Couldn’t fetch matches",
        "حاول التحديث بالسحب للأسفل": "Try refreshing by pulling down",
        "أدوار البطولة": "Competition Rounds",
        "الجاري الآن": "In progress now",
        "لا توجد مباريات معتمدة لهذا الدور بعد": "No confirmed matches for this round yet",
        "لم تصل بيانات جدول كأس العالم بعد": "World Cup schedule data hasn’t arrived yet",
        "اليوم %@": "Today %@",
        "غدًا %@": "Tomorrow %@",
        "بعد غد %@": "Day after tomorrow %@",
        "لا انتقالات": "No transfers",
        "لا توجد صفقات معلنة حاليًا": "No announced deals right now",
        "تعذّر الاتصال بخادم بيانات كأس العالم": "Couldn’t reach the World Cup data server",
        "بطولاتي": "My Competitions",
        "إزالة من بطولاتي": "Remove from My Competitions",
        "إضافة إلى بطولاتي": "Add to My Competitions",
        "قريبًا": "Soon",
        "انتهى": "Ended",
        "فِرقك": "Your Teams",
        "آخر توقّعاتك": "Your Latest Predictions",
        "لم تتوقّع بعد": "No predictions yet",
        "ابدأ من تبويب «روشن» ← التوقّعات": "Start from the “Roshn” tab → Predictions",
        "سجّل الدخول": "Sign In",
        "لتظهر هنا توقّعاتك وفرقك وتنبيهاتك": "To see your predictions, teams, and alerts here",
        "تطبيق VARA الرياضي السعودي يجمع المباريات والبطولات والتوقّعات الذكية في مكانٍ واحد — بتصميمٍ نظيف وأرقام حيّة.": "The Saudi sports app VARA brings matches, competitions, and smart predictions together in one place — with a clean design and live numbers.",
        "من سبق": "From Sabq",
        "تطبيق VARA أحد منتجات صحيفة سبق الإلكترونية. تدخل بعضوية سبق نفسها، وتتابع الرياضة بهوية سعودية من قلب سبق.": "The VARA app is a product of Sabq electronic newspaper. You sign in with the same Sabq membership, and follow sports with a Saudi identity from the heart of Sabq.",
        "ما الذي يقدّمه VARA؟": "What does VARA offer?",
        "جدول المباريات بالتواريخ مع التنقّل الزمني السلس بين الأدوار والأيام.": "A dated match schedule with smooth navigation between rounds and days.",
        "مركز مباراة غنيّ: الأحداث، الإحصائيات، التشكيلات، التقييمات، والمواجهات.": "A rich match center: events, stats, lineups, ratings, and head-to-head records.",
        "«توقّع VARA» الذكي: خوارزمية ديناميكية تحسب احتمالات النتيجة من الترتيب والفورمة وأفضلية الأرض.": "Smart “VARA Prediction”: a dynamic algorithm that computes outcome odds from standings, form, and home advantage.",
        "تنبيهات لحظية لمبارياتك وفِرقك (أهداف، بطاقات، فار، بداية ونهاية).": "Instant alerts for your matches and teams (goals, cards, VAR, kickoff, and full time).",
        "متابعة الفِرق والمباريات + بطاقة «مبارياتي» مع عدّاد تنازليّ حيّ.": "Follow teams and matches, plus a “My Matches” card with a live countdown.",
        "مصادر البيانات": "Data Sources",
        "تُجمع نتائج المباريات والإحصاءات من مزوّدي بيانات رياضية متخصّصين، وقد تتأخّر أو تختلف قليلًا عن المصادر الرسمية. وتبقى توقّعات التطبيق تقديرية للمتعة والتحليل فقط.": "Match results and stats are collected from specialized sports data providers, and may lag or differ slightly from official sources. App predictions remain estimates for fun and analysis only.",
        "النسخة الحالية: %@.": "Current version: %@.",
        "تنظّم هذه السياسة طريقة استخدامك لتطبيق VARA لضمان تجربة عادلة وآمنة للجميع.": "This policy governs how you use the VARA app to ensure a fair and safe experience for everyone.",
        "الاستخدام المقبول": "Acceptable Use",
        "VARA متاحٌ للاستخدام الشخصي غير التجاري. يُمنع إساءة استخدام الخدمة أو محاولة تعطيلها أو استخراج بياناتها آليًّا دون إذن.": "VARA is available for personal, non-commercial use. Misusing the service, attempting to disrupt it, or automatically scraping its data without permission is prohibited.",
        "التوقّعات للمتعة فقط": "Predictions Are for Fun Only",
        "نظام «توقّع VARA» ولوحة المتصدّرين للمنافسة والتسلية فقط — لا رهان ولا مقابل ماديّ، والنقاط رمزية ولا تمثّل قيمة نقدية.": "The “VARA Prediction” system and leaderboard are for competition and entertainment only — no wagering or monetary reward, and points are symbolic with no cash value.",
        "دقّة المحتوى": "Content Accuracy",
        "نسعى لعرض بيانات دقيقة وحيّة، لكنّنا لا نضمن خلوّها من الأخطاء أو التأخّر. القرارات المبنية على هذه البيانات تقع على مسؤوليتك.": "We strive to show accurate, live data, but we do not guarantee it is free of errors or delays. Decisions based on this data are your own responsibility.",
        "الحساب والخصوصية": "Account & Privacy",
        "أنت مسؤول عن الحفاظ على سرّية بيانات حسابك. تُستخدم بياناتك لتقديم الخدمة وتخصيص التنبيهات والتوقّعات، ويمكنك حذف حسابك وبياناتك في أي وقت من الإعدادات.": "You are responsible for keeping your account details confidential. Your data is used to provide the service and personalize alerts and predictions, and you can delete your account and data at any time from Settings.",
        "بتفعيلك للتنبيهات توافق على استقبال إشعارات عن مبارياتك وفِرقك. يمكنك إيقافها في أي وقت من إعدادات التطبيق أو النظام.": "By enabling alerts, you agree to receive notifications about your matches and teams. You can turn them off at any time from the app or system settings.",
        "باستخدامك تطبيق VARA فإنك توافق على الشروط التالية.": "By using the VARA app, you agree to the following terms.",
        "قبول الشروط": "Acceptance of Terms",
        "يُعدّ تنزيلك أو استخدامك للتطبيق موافقةً على هذه الشروط. إن لم توافق عليها، يُرجى التوقّف عن استخدام التطبيق.": "Downloading or using the app constitutes agreement to these terms. If you do not agree, please stop using the app.",
        "الحساب": "Account",
        "تلتزم بتقديم معلومات صحيحة عند إنشاء الحساب، وبعدم انتحال هويّة الغير. نحتفظ بحقّ تعليق الحسابات المخالفة.": "You agree to provide accurate information when creating an account and not to impersonate others. We reserve the right to suspend accounts that violate these terms.",
        "الملكية الفكرية": "Intellectual Property",
        "علامة VARA وتصميم التطبيق وواجهاته مملوكة لصحيفة سبق الإلكترونية. لا يجوز نسخها أو إعادة نشرها دون إذن. تبقى حقوق بيانات المباريات لمزوّديها.": "The VARA trademark, app design, and interfaces are owned by Sabq electronic newspaper. They may not be copied or republished without permission. Match data rights remain with their providers.",
        "حدود المسؤولية": "Limitation of Liability",
        "يُقدَّم التطبيق «كما هو» دون ضمانات. لا نتحمّل مسؤولية أي خسارة ناتجة عن انقطاع الخدمة أو أخطاء البيانات أو التوقّعات.": "The app is provided “as is” without warranties. We are not liable for any loss resulting from service interruptions, data errors, or predictions.",
        "تعديل الشروط": "Changes to the Terms",
        "قد نحدّث هذه الشروط من وقتٍ لآخر، ويسري التعديل فور نشره داخل التطبيق.": "We may update these terms from time to time, and changes take effect as soon as they are published in the app.",
        "إجراء نهائيّ لا يمكن التراجع عنه.": "A permanent action that cannot be undone.",
        "عند الحذف سيتمّ:": "Deleting your account will:",
        "حذف ملفّك الشخصي وبيانات دخولك نهائيًّا.": "Permanently delete your profile and login data.",
        "حذف فِرقك المتابَعة وتفضيلات التنبيهات.": "Delete your followed teams and alert preferences.",
        "حذف توقّعاتك ونقاطك في لوحة المتصدّرين.": "Delete your predictions and leaderboard points.",
        "إلغاء تسجيل أجهزتك من الإشعارات.": "Unregister your devices from notifications.",
        "أدخل كلمة المرور للتأكيد": "Enter your password to confirm",
        "حذف حسابي نهائيًّا": "Permanently Delete My Account",
        "تأكيد حذف الحساب": "Confirm Account Deletion",
        "حذف نهائيّ": "Delete Permanently",
        "سيتمّ حذف حسابك وكل بياناتك نهائيًّا ولا يمكن استرجاعها.": "Your account and all your data will be permanently deleted and cannot be recovered.",
        "لا مباريات مباشرة عالميًا الآن": "No live matches worldwide right now",
        "ستظهر هنا أي مباراة جارية الآن حول العالم": "Any match currently underway around the world will appear here",
        "المباريات الجارية حول العالم": "Matches underway around the world",
        "%d مباشرة": "%d live",
        "بطولات أخرى": "Other competitions",
        "%@ مباشرة": "%@ live",
        "دور المجموعات": "Group Stage",
        "دور الـ32": "Round of 32",
        "دور الـ16": "Round of 16",
        "ربع النهائي": "Quarter-finals",
        "نصف النهائي": "Semi-finals",
        "المركز الثالث": "Third Place",
        "النهائي": "Final",
        "المجموعات": "Groups",
        "الـ32": "R32",
        "الـ16": "R16",
        "ربع": "QF",
        "نصف": "SF",
        "الثالث": "3rd",
        "حاول لاحقًا": "Try again later",
        "اليوم · %@ %@": "Today · %@ %@",
        "غدًا · %@ %@": "Tomorrow · %@ %@",
        "أمس · %@ %@": "Yesterday · %@ %@",
        "موعد": "Scheduled",
        "ترجيح": "Pens",
        "استراحة": "Half-time",
        "استراحة إضافي": "Extra-time break",
        "ركلات": "Penalties",
        "موقوفة": "Suspended",
        "متوقّفة": "Stopped",
        "لم تبدأ": "Not started",
        "الزخم والاستحواذ": "Momentum & Possession",
        "الاستحواذ": "Possession",
        "لم تُعلَن التشكيلة بعد": "Lineup not announced yet",
        "الإحصائيات": "Stats",
        "التوقع": "Prediction",
        "من دور الـ32 حتى النهائي": "From Round of 32 to Final",
        "مباراة %d": "Match %d",
        "بانتظار التأهل": "Awaiting qualification",
        "مباشرة": "Live",
        "توقّعي": "My Prediction",
        "لم تُصب": "Missed",
        "بانتظار النتيجة": "Awaiting Result",
        "خليجي 27": "Gulf Cup 27",
        "كأس العالم": "World Cup",
        "دوري الأبطال": "Champions League",
        "%@ (أنت)": "%@ (You)",
        "%d دقيقة · دقّة %d٪ · %d توقّع": "%d exact · %d%% accuracy · %d picks",
        "لا بطولات متاحة": "No competitions available",
        "توقّعات البطل والهدّاف تظهر للبطولات الجارية": "Champion and top-scorer predictions appear for ongoing competitions",
        "توقّع البطل": "Champion Prediction",
        "قوائم الفرق غير متاحة بعد لهذه البطولة": "Team lists aren't available yet for this competition",
        "توقّع الهدّاف": "Top Scorer Prediction",
        "أُقفلت التوقّعات — انطلقت البطولة": "Predictions are locked — the competition has started",
        "اكتب اسم اللاعب…": "Type player name…",
        "سجّل الدخول لتوقّع الهدّاف": "Sign in to predict the top scorer",
        "اختيارك الحالي: %@": "Your current pick: %@",
        "تم الحفظ ✓": "Saved ✓",
        "العرّاف": "The Oracle",
        "5 نتائج دقيقة": "5 exact scores",
        "قلب الأسد": "Lionheart",
        "أصبت نتيجة مفاجئة (احتمال أقل من 10٪)": "Called an upset (under 10% probability)",
        "سلسلة ملتهبة": "Hot Streak",
        "3 توقّعات صحيحة متتالية": "3 correct predictions in a row",
        "الماراثوني": "The Marathoner",
        "25 توقّعًا مكتملًا": "25 completed predictions",
        "جمعت %d من %d شارة": "Earned %d of %d badges",
        "مكتمل ✓": "Completed ✓",
        "مقفل": "Locked",
        "توقّع موفّق! 🎉": "Great pick! 🎉",
        "%@ ضد %@": "%@ vs %@",
        "نقطة من %@": "pts from %@",
        "رائع!": "Great!",
        "توقّعي في VARA": "My Prediction on VARA",
        "شارك إنجازك": "Share your achievement",
        "أصبت النتيجة بدقّة 🎯": "Nailed the exact score 🎯",
        "النتيجة النهائية ": "Final score ",
        "+%d نقطة · %@": "+%d pts · %@",
        "توقّع معي في تطبيق VARA الرياضي": "Predict with me on the VARA Sports app",
        "الهداف الفعلي: %@": "Actual scorer: %@",
        "+%d نقطة": "+%d pts",
        "بانتظار المباراة": "Awaiting kickoff",
        "توقّع هدّاف المباراة": "Predict the Match Scorer",
        "بركة %d": "%d-point pool",
        "اختر هدّافًا": "Choose a scorer",
        "تغيير": "Change",
        "توقّعت: %@": "You picked: %@",
        "أُقفل التوقّع — انطلقت المباراة": "Prediction locked — match has kicked off",
        "هذا اللاعب ليس ضمن قائمة المباراة": "This player isn't in the match lineup",
        "هذه المباراة غير متاحة للتوقّع": "This match isn't open for predictions",
        "اختر %@": "Choose %@",
        "ابحث عن لاعب": "Search for a player",
        "أساسي": "Starting",
        "احتياط": "Substitute",
        "التشكيلات لم تُعلَن بعد": "Lineups haven't been announced yet",
        "تنزل تشكيلتا الفريقين عادةً قبل المباراة بساعة. عُد لاحقًا لاختيار الهداف.": "Both lineups usually drop about an hour before kickoff. Check back later to pick a scorer.",
        "تعذّر تحميل اللاعبين": "Couldn't load players",
        "النتيجة الدقيقة": "Exact Score",
        "الفارق الصحيح": "Correct Margin",
        "النتيجة الصحيحة": "Correct Result",
        "هداف المباراة": "Match Top Scorer",
        "أول هدّاف": "First Scorer",
        "توقّعاتي": "My Predictions",
        "الهدافون": "Scorers",
        "المتصدّرون": "Leaders",
        "البطل والهدّاف": "Champion & Top Scorer",
        "الإنجازات": "Achievements",
        "كيف تلعب؟": "How to Play?",
        "المسابقة قريبًا": "Competition coming soon",
        "نظام التوقّعات المتطوّر سيُفتح قريبًا — ترقّبه!": "Our advanced prediction system launches soon — stay tuned!",
        "الجائزة المتراكمة": "Jackpot",
        "دقيقة": "min",
        "صحيحة": "Correct",
        "سلسلة": "Streak",
        "سجّل الدخول من «حسابي» للمنافسة وجمع النقاط.": "Sign in from “Account” to compete and earn points.",
        "سلسلة ملتهبة! واصل نحو %d متتالية": "On fire! Keep going to %d in a row",
        "سلسلتك %d/%d نحو شارة «سلسلة ملتهبة»": "Your streak: %d/%d toward the “On Fire” badge",
        "فارق": "Margin",
        "نتيجة": "Result",
        "50٪": "50%",
        "30٪": "30%",
        "20٪": "20%",
        "%@ من البركة": "%@ of the pool",
        "قسمك هذا الأسبوع: %@": "Your division this week: %@",
        "%d نقطة الأسبوع": "%d pts this week",
        "%d للموسم": "%d for the season",
        "النوّاحة": "Oracles",
        "المحلّلون": "Analysts",
        "المتابعون": "Followers",
        "الجمهور": "Crowd",
        "لا مباريات للتوقّع الآن": "No matches to predict right now",
        "تظهر هنا مباريات اليوم والغد القابلة للتوقّع": "Today’s and tomorrow’s predictable matches appear here",
        "ابدأ من تبويب «المباريات» وستظهر توقّعاتك هنا": "Start from the “Matches” tab and your predictions will appear here",
        "لم تتوقّع هدّافًا بعد": "No scorer predictions yet",
        "اختر هدّاف كل مباراة من بطاقتها — ستظهر توقّعاتك هنا": "Pick each match’s scorer from its card — your predictions will appear here",
        "كن أول من يتصدّر بتوقّعاتك": "Be the first to top the leaderboard with your predictions",
        "ادخل من تبويب «حسابي» للتوقّع والمنافسة على النقاط": "Sign in from the “Account” tab to predict and compete for points",
        "الفكرة من الألف للياء": "The Concept, A to Z",
        "ما هذا؟": "What Is This?",
        "لعبة توقّع مجانيّة بالكامل — لا تدفع شيئًا للمشاركة، والمكافآت كلّها نقاط ولاء قابلة للاستبدال داخل التطبيق.": "A completely free prediction game — you pay nothing to participate, and all rewards are loyalty points redeemable inside the app.",
        "توقّع ثم انتظر": "Predict, Then Wait",
        "اختر نتيجة كل مباراة (وهدافها) قبل انطلاقها، ثم تُسوّى تلقائيًا فور انتهائها.": "Pick each match’s result (and its scorer) before kickoff, then it’s settled automatically once the match ends.",
        "كلّما قلّ المصيبون زاد نصيبك": "The Fewer the Winners, the Bigger Your Share",
        "النقاط لا تُمنح من رأس مال — بل تُقتسم بين المصيبين. فلو أصبت وحدك، أخذت البركة كاملة.": "Points aren’t granted from a fixed pot — they’re split among the winners. If you’re the only one who gets it right, you take the whole pool.",
        "ارفع طبقتك وتصدّر": "Level Up and Lead",
        "نقاطك تُضاف لرصيد ولائك وتُرقّيك بين 5 طبقات، وفي الأسبوع تُرتّب في 4 أقسام متفاوتة.": "Your points add to your loyalty balance and promote you across 5 tiers, and each week you’re ranked into 4 divisions.",
        "ليست رهانًا — كيف؟": "Not Gambling — Here’s How",
        "دخول مجّاني": "Free Entry",
        "لا تدفع مبلغًا ولا تخاطر بشيء. المشاركة مفتوحة لكل المستخدمين بلا مقابل.": "You pay nothing and risk nothing. Participation is open to all users at no cost.",
        "سبق تموّل الجوائز": "Sabq Funds the Prizes",
        "بركة كل مباراة يدفعها تطبيق سبق من ميزانيته التسويقية، لا من خسائر المستخدمين.": "Each match’s pool is paid by the Sabq app from its marketing budget, not from users’ losses.",
        "توزيع عادل شفّاف": "Fair, Transparent Distribution",
        "البركة تُقسَّم بالتساوي بين المصيبين وفق قواعد معلنة — لا احتمالات يعدّلها أحد لصالحه.": "The pool is split equally among the winners according to published rules — no odds are adjusted in anyone’s favor.",
        "مكافآت داخل التطبيق": "In-App Rewards",
        "النقاط تُستبدل مزايا وجوائز داخل سبق، لا يمكن سحبها نقدًا.": "Points are redeemed for perks and prizes inside Sabq — they can’t be withdrawn as cash.",
        "طبقات النتيجة — بركة 1000": "Score Tiers — 1,000-Point Pool",
        "🎯 النتيجة الدقيقة — 50٪": "🎯 Exact Score — 50%",
        "أصبت الرقمين بالضبط (مثال 2-1). نصيبك من البركة = 500 نقطة تُقسَّم على المصيبين.": "You got both numbers exactly right (e.g. 2-1). Your share of the pool = 500 points split among the winners.",
        "📏 الفارق الصحيح — 30٪": "📏 Correct Margin — 30%",
        "أصبت الفارق والاتجاه لا الرقمين (مثال توقّعت 3-1 وانتهت 2-0). نصيبك = 300 نقطة تُقسَّم.": "You got the margin and direction right, not the exact numbers (e.g. you predicted 3-1 and it ended 2-0). Your share = 300 points, split.",
        "✅ النتيجة الصحيحة — 20٪": "✅ Correct Result — 20%",
        "أصبت الفائز أو التعادل فقط. نصيبك = 200 نقطة تُقسَّم على المصيبين.": "You got only the winner or the draw right. Your share = 200 points split among the winners.",
        "النتيجة المقلوبة لا تفوز": "A Flipped Score Doesn’t Win",
        "من أصاب الفائز لكن قلب الرقمين (توقّع 1-2 وانتهت 2-1) لا يُكافأ.": "Getting the winner right but reversing the numbers (predicting 1-2 when it ends 2-1) isn’t rewarded.",
        "الجائزة المتراكمة (الجاكبوت)": "The Accumulated Prize (Jackpot)",
        "متى يتراكم؟": "When Does It Build Up?",
        "عندما لا يُصب أحدٌ طبقةً (مثلاً نتيجة مفاجئة)، تترحّل نقاط تلك الطبقة للمباراة التالية في البطولة نفسها.": "When no one gets a tier right (say, a surprise result), that tier’s points roll over to the next match in the same competition.",
        "لماذا يكبر؟": "Why Does It Grow?",
        "كل مباراة بلا فائز تُضيف نقاطها للتي بعدها، فتتضخّم الجائزة حتى يأتي من يصيبها.": "Every match with no winner adds its points to the next one, swelling the prize until someone finally gets it right.",
        "لكل بطولة جاكبوتها": "Every Competition Has Its Own Jackpot",
        "الجاكبوت مستقلّ لكل بطولة — كأس العالم له جاكبوت، ودوري روشن له آخر، وهكذا.": "The jackpot is independent per competition — the World Cup has its own, the Roshn League has another, and so on.",
        "توقّع الهداف ⚽": "Predict the Scorer ⚽",
        "هداف المباراة — بركة 300": "Match Scorer — 300-Point Pool",
        "إضافةً لتوقّع النتيجة، اختر من سيسجّل. أصبت؟ تأخذ حصّتك من بركة 300 نقطة تُقسَّم على المصيبين.": "On top of predicting the result, pick who’ll score. Get it right and you take your share of a 300-point pool split among the winners.",
        "أول هدّاف — بركة 200": "First Scorer — 200-Point Pool",
        "اختر من سيفتتح التسجيل. بركة أصغر لكن مكافأة أعلى لأنّ التحدّي أصعب.": "Pick who’ll open the scoring. A smaller pool, but a bigger payoff because it’s a tougher call.",
        "من قائمة اللاعبين الفعليّين": "From the Actual Squad List",
        "تختار من تشكيلتي الفريقين اللتين تنزلان قبل المباراة. الأساسيّون والاحتياط ظاهرون.": "You choose from both teams’ lineups released before kickoff. Starters and substitutes are both shown.",
        "قبل الانطلاق فقط": "Before Kickoff Only",
        "يُقفل توقّع الهداف مع بداية المباراة تمامًا كتوقّع النتيجة.": "Scorer predictions lock at kickoff, exactly like the result prediction.",
        "مضاعف الولاء 🔮": "Loyalty Multiplier 🔮",
        "كلّما ارتفع ولاؤك زاد نصيبك": "The Higher Your Loyalty, the Bigger Your Share",
        "حصّتك من البركة تُضرب بمضاعف حسب طبقة ولائك: من 1.0× للقارئ الجديد إلى 1.5× لسفير سبق.": "Your share of the pool is multiplied based on your loyalty tier: from 1.0× for a new reader up to 1.5× for a Sabq Ambassador.",
        "مثال محسوب": "A Worked Example",
        "أصبت النتيجة الدقيقة ونصيبك 100 نقطة، وطبقتك «العضو الذهبي» (1.2×) → تحصل على 120 نقطة فعلية.": "You got the exact score right and your share is 100 points, with your tier at “Gold Member” (1.2×) → you actually receive 120 points.",
        "كيف أرفع طبقتي؟": "How Do I Level Up My Tier?",
        "بالقراءة والتفاعل اليومي والمشاركة المنتظمة — لا بتوقّع واحد كبير. ولاؤك تراكمي طويل المدى.": "Through daily reading, engagement, and regular participation — not one big prediction. Your loyalty builds up over the long term.",
        "الأقسام الأسبوعية 🏆": "Weekly Divisions 🏆",
        "4 أقسام متفاوتة": "4 Tiered Divisions",
        "كل يوم سبت يُوزَّع المتنافسون على 4 أقسام حسب نقاطهم في الأسبوع: النوّاحة 🔮 · المحلّلون ⭐ · المتابعون 🎯 · الجمهور 👀.": "Every Saturday, competitors are sorted into 4 divisions by their points that week: Oracles 🔮 · Analysts ⭐ · Followers 🎯 · Crowd 👀.",
        "ترقية وهبوط كل أسبوع": "Promotion and Relegation Every Week",
        "تُحسب نقاطك يوم السبت، فإن تحسّنت صعدت قسمًا أعلى، وإن تراجعت هبطت. إشعار يصلك بالتغيّر.": "Your points are tallied on Saturday — improve and you move up a division, slip and you move down. Either way, you’ll get a notification.",
        "أعلى 1٪ في النوّاحة": "Top 1% in Oracles",
        "القسم الأعلى يضمّ نخبة المتنبّئين في الأسبوع — شرفٌ ومكانة تظهر في ملفّك.": "The top division holds the week’s elite predictors — an honor and status that shows on your profile.",
        "في أيّ يوم؟": "On What Day?",
        "تُحسب الأقسام فجر كل سبت (00:00 بتوقيت الرياض) من نقاط الأسبوع المنتهي.": "Divisions are calculated at dawn every Saturday (00:00 Riyadh time) from the points of the week that just ended.",
        "البطل والهداف — توقّعات البطولة": "Champion & Top Scorer — Tournament Predictions",
        "بركة 5000 لكل نوع": "5,000-Point Pool for Each",
        "توقّع من سيفوز بالبطولة ومن سيكون هدّافها. بركة منفصلة 5000 لكل نوع تُسوّى عند ختام البطولة.": "Predict who’ll win the tournament and who’ll be its top scorer. A separate 5,000-point pool for each is settled at the end of the tournament.",
        "مفتوحة حتى دور الثمانية": "Open Until the Quarterfinals",
        "تبقى هذه التوقّعات متاحة حتى انطلاق ربع النهائي ثم تُقفل نهائيًا.": "These predictions stay open until the quarterfinals kick off, then lock permanently.",
        "مكافأة متأخّرة": "A Delayed Reward",
        "هذه التوقّعات لا تُسوّى إلا في نهاية البطولة — صبرك فيها يُكافأ بنقاط كبيرة.": "These predictions only settle at the end of the tournament — your patience is rewarded with big points.",
        "الإنجازات والشارات 🏅": "Achievements & Badges 🏅",
        "شارات دائمة": "Permanent Badges",
        "أصبت 5 نتائج دقيقة متتالية؟ تنال شارة «نوستراداموس». هذه الشارات تظهر في ملفّك للأبد.": "Get 5 exact scores in a row? You earn the “Nostradamus” badge. These badges stay on your profile forever.",
        "أنواع متعدّدة": "Multiple Types",
        "هناك شارات للدقّة، وللجرأة (توقّعت المفاجأة وأصبت)، وللاستمرار، وللهدافين — كلٌّ بقواعدها.": "There are badges for accuracy, boldness (calling an upset correctly), consistency, and scorer picks — each with its own rules.",
        "مكافأة فورية": "Instant Reward",
        "كلّ شارة جديدة تمنحك نقاط ولاء إضافية لحظة نيلها.": "Every new badge grants you extra loyalty points the moment you earn it.",
        "🔒 التوقّعات للمتعة والمنافسة فقط — لا رهان ولا مقابل مادّي. كل المكافآت نقاط ولاء داخل تطبيق سبق.": "🔒 Predictions are for fun and competition only — no gambling, no monetary stakes. All rewards are loyalty points within the Sabq app.",
        "جرّب اسمًا آخر — نبحث في البطولات وأندية روشن ومنتخبات المونديال": "Try another name — we search competitions, Roshn clubs, and World Cup teams",
        "أندية ومنتخبات": "Clubs & national teams",
        "بطولات": "Competitions",
        "ابحث عن نادٍ أو منتخب أو بطولة": "Search for a club, national team, or competition",
        "مسح البحث": "Clear search",
        "اكتب للبحث في:": "Type to search in:",
        "كل البطولات المتاحة": "All available competitions",
        "أندية دوري روشن": "Roshn League clubs",
        "منتخبات كأس العالم 2026": "2026 World Cup national teams",
        "كأس العالم 2026": "2026 World Cup",
        "كأس الملك": "King's Cup",
        "كأس السوبر السعودي": "Saudi Super Cup",
        "دوري يلو": "Yelo League",
        "دوري الدرجة الثانية": "Second Division League",
        "الدوري السعودي للسيدات": "Saudi Women's League",
        "الدوري الإنجليزي": "English Premier League",
        "الدوري الإسباني": "La Liga",
        "الدوري الإيطالي": "Serie A",
        "الدوري الألماني": "Bundesliga",
        "الدوري الفرنسي": "Ligue 1",
        "مباراة مباشرة": "Live Match",
        "جارية / مقفلة": "Live / Locked",
        "زيادة الأهداف": "Increase goals",
        "إنقاص الأهداف": "Decrease goals",
        "سجّل الدخول للتوقّع على هذه المباراة": "Sign in to predict this match",
        "توقّعك: ": "Your prediction: ",
        "توقّعك %@": "Your prediction %@",
        "· بانتظار النتيجة": "· Awaiting result",
        "لا يمكن توقع التعادل في خروج المغلوب — اختر فائزًا للمباراة": "Draws aren’t allowed in knockout matches — pick a winner",
        "انتهت المباراة — لم تتوقّع": "Match ended — no prediction made",
        "فوز %@": "%@ win",
        "الجمهور (%d): %d٪ مضيف · %d٪ تعادل · %d٪ ضيف": "Crowd (%d): %d%% home · %d%% draw · %d%% away",
        "البركة المتاحة": "Available Pool",
        "النتيجة": "Result",
        "سجّل الدخول لتصلك إشعارات الأهداف والنتيجة لحظيًّا": "Sign in to get instant goal and score alerts",
        "مبارياتي": "My Matches",
        "مباريات من بطولات مختلفة": "Matches from different competitions",
        "بعد غد": "Day after tomorrow",
        "تبدأ بعد": "Starts in",
        "انتهت · تختفي بعد قليل": "Ended · disappearing shortly",
        "%dي %dس": "%dd %dh",
        "لا مباريات قادمة مجدولة حاليًا": "No upcoming matches scheduled right now",
        "مباريات %@ القادمة": "%@’s Upcoming Matches",
        "صفحة الفريق": "Team page",
        "اختر فريقك المفضّل": "Choose your favorite team",
        "تابع مبارياته عبر كل البطولات من هنا — النجمة في صفحة النادي": "Follow its matches across every competition here — the star on the club page",
        "انطلق الموسم — تابع المباريات الآن": "Season underway — follow the matches now",
        "يوم": "day",
        "ساعة": "hour",
        "ثانية": "second",
        "انطلاق الموسم القادم": "Next Season Kickoff",
        "مباريات الافتتاح": "Opening Matches",
        "في العطلة": "On break",
        "استعداد للموسم": "Preparing for the Season",
        "نظرة الموسم": "Season Outlook",
        "بانتظار جدول الموسم الجديد — وإليك بطل الموسم الماضي.": "Waiting for the new season’s schedule — meanwhile, here’s last season’s champion.",
        "العدّ التنازلي لانطلاق الموسم الجديد ومبارياته الأولى.": "The countdown to the new season and its opening matches.",
        "كل ما يخصّ الموسم في مكان واحد.": "Everything about the season in one place.",
        "عاجل": "Breaking",
        "VARA الرياضي": "VARA Sports",
        "· %d دقيقة": "· %d min",
        "%@ — عبر VARA": "%@ — via VARA",
        "المفضّل": "Favorite",
        "اجعله المفضّل": "Make Favorite",
        "تتابع التنبيهات": "Following Alerts",
        "تابع التنبيهات": "Follow Alerts",
        "التأسيس": "Founded",
        "حجم القائمة": "Squad Size",
        "المدرّب": "Coach",
        "%d سنة": "%d yrs",
        "الإصابات والغيابات": "Injuries & Absences",
        "العودة: %@": "Return: %@",
        "مباريات": "Matches",
        "فوز": "Wins",
        "خسارة": "Losses",
        "أهداف له": "Goals For",
        "أهداف عليه": "Goals Against",
        "شِباك نظيفة": "Clean Sheets",
        "بطاقات": "Cards",
        "التشكيل الأكثر": "Most Used Formation",
        "أطول سلسلة فوز": "Longest Win Streak",
        "أرقام الفريق في الموسم": "Team Stats This Season",
        "آخر الانتقالات": "Latest Transfers",
        "واصلون": "Arrivals",
        "مغادرون": "Departures",
        "من ": "From ",
        "إلى ": "To ",
        "لا توجد مباريات معلنة بعد": "No matches announced yet",
        "المباريات القادمة": "Upcoming Matches",
        "هدّافو الفريق": "Team Scorers",
        "القائمة": "Squad",
        "القائمة الرسمية لم تُعلن بعد": "Official squad not announced yet",
        "بطاقة اللاعب": "Player Card",
        "اللاعب": "Player",
        "%d سم": "%d cm",
        "العمر": "Age",
        "الطول": "Height",
        "%d كجم": "%d kg",
        "الوزن": "Weight",
        "القيمة السوقية": "Market Value",
        "الذروة": "Peak",
        "%.1f مليون %@": "%.1fM %@",
        "%.0f ألف %@": "%.0fK %@",
        "أرقام الموسم": "Season Stats",
        "دقائق": "Minutes",
        "أهداف": "Goals",
        "تصديات": "Saves",
        "استقبلها": "Conceded",
        "الفورمة الأخيرة · xG": "Recent Form · xG",
        "آخر %d": "Last %d",
        "الخصم": "Opponent",
        "أرضه": "Home",
        "خارج أرضه": "Away",
        "سجل المواسم": "Season History",
        "مباراة": "Match",
        "المسيرة": "Career",
        "الألقاب": "Trophies",
        "%d بطولة": "%d titles",
        "مؤكّدة": "Confirmed",
        "إشاعة": "Rumour",
        "القصة الأبرز": "Featured Story",
        "القصص الأبرز": "Top Stories",
        "القيمة المتداولة": "Reported Value",
        "غير معلنة": "Undisclosed",
        "%d يومًا و%d ساعة": "%d days, %d hours",
        "%d ساعة و%d دقيقة": "%d hours, %d minutes",
        "تفتح بعد %@": "Opens in %@",
        "تُغلق بعد %@": "Closes in %@",
        "أُغلقت النافذة": "Window closed",
        "· %d %@": "· %d %@",
        "صفقة": "deal",
        "قيم الميركاتو المتداولة: روشن مقابل البريميرليغ": "Reported market values: Roshn vs. Premier League",
        "إنفاق الميركاتو: روشن مقابل البريميرليغ": "Market spending: Roshn vs. Premier League",
        "🇸🇦 دوري روشن السعودي": "🇸🇦 Saudi Roshn League",
        "🏴 البريميرليغ": "🏴 Premier League",
        "قيم متداولة في إشاعات المصادر منذ مطلع يونيو — تتحوّل إلى الصفقات الرسمية فور توفّر سجل النافذة.": "Values reported in source rumours since early June — they convert to official deals once the window's record is available.",
        "الصفقات المُعلَنة المبالغ فقط منذ مطلع يونيو.": "Deals with publicly disclosed fees only, since early June.",
        "ميزان السوق — أندية روشن هذا الميركاتو": "Market Balance — Roshn Clubs This Window",
        "صرف": "Spent",
        "دخل": "Earned",
        "إشاعات": "Rumours",
        "إعارات": "Loans",
        "تجديد": "Renewals",
        "نبض سوق الانتقالات": "Transfer Market Pulse",
        "الصفقات المؤكدة والإشاعات مرتبة حسب الحالة والمصدر.": "Confirmed deals and rumours, sorted by status and source.",
        "مؤكدة": "Confirmed",
        "بارزة": "Featured",
        "تصفية السوق": "Market Filters",
        "كل الدرجات": "All Levels",
        "وشيكة": "Imminent",
        "قوية": "Strong",
        "متوسطة": "Medium",
        "ضعيفة": "Weak",
        "أبرز الأندية": "Top Clubs",
        "كل الانتقالات": "All Transfers",
        "لا صفقات مؤكّدة": "No confirmed deals",
        "لا حركة انتقالات مؤكّدة في النافذة الحالية.": "No confirmed transfer activity in the current window.",
        "صفقة مؤكّدة": "confirmed deals",
        "جرّب «كل الانتقالات».": "Try “All Transfers.”",
        "انتقالًا": "transfers",
        "لا إشاعات مطابقة": "No matching rumours",
        "تغطية المصادر العالمية للدوري السعودي تتحرّك مع اشتعال السوق.": "Global source coverage of the Saudi league picks up as the market heats up.",
        "جرّب تغيير الفلاتر.": "Try changing the filters.",
        "إشاعة — كل إشاعة بمصدرها ودرجة احتمالها": "rumours — each with its source and probability level",
        "الصفقات المؤكّدة من سجل API-Football، والإشاعات من رصد SportMonks لمصادر عالمية (فابريزيو رومانو، الغارديان، ESPN…) وتبقى إشاعةً حتى إعلانها رسميًّا. مؤشر الموثوقية تصنيف تحريري من سبق، ولا نعرض مبلغًا لم يُعلَن.": "Confirmed deals come from the API-Football record, and rumours from SportMonks' tracking of global sources (Fabrizio Romano, The Guardian, ESPN…) and remain rumours until officially announced. The reliability indicator is an editorial classification by Sabq, and we never show an undisclosed fee.",
        "سعودية": "Saudi",
        "%d صفقة": "%d deals",
        "%d انتقال": "%d transfers",
        "تحميل": "Loading",
        "%d إشاعة": "%d rumours",
        "%d %@": "%d %@",
        "لا قصة موثّقة": "No documented story",
        "لا توجد قصة انتقال موثّقة لهذا اللاعب حاليًا.": "There's no documented transfer story for this player right now.",
        "قصة الانتقال": "Transfer Story",
        "%d عامًا": "%d years old",
        "قصة إشاعات — لم تتأكّد بعد": "Rumour story — not yet confirmed",
        "انتقال": "Transfer",
        "تجديد عقد": "Contract renewal",
        "آخر تحديث: %@": "Last updated: %@",
        "تسلسل القصة": "Story Timeline",
        "%d تطوّرًا — تصاعديًّا مع درجة احتمال كل مرحلة ومصدرها": "%d developments — chronological, with each stage's probability and source",
        "أخبار ذات صلة": "Related News",
        "درجة الاحتمال والمبلغ المتداول من المصدر المذكور في كل مرحلة (رصد SportMonks)، ومؤشر الموثوقية تصنيف تحريري من سبق. تبقى القصة إشاعةً حتى إعلانها رسميًّا من الناديين.": "The probability level and reported fee at each stage come from the source named (SportMonks tracking), and the reliability indicator is an editorial classification by Sabq. The story remains a rumour until officially announced by both clubs.",
        "ذكاء VARA": "VARA Insights",
        "نتيجة التوقّعات": "Prediction Results",
        "أصاب النتيجة بدقّة": "Exact score",
        "أصاب الاتجاه": "Right direction",
        "لم يُصب": "Missed",

        // ── سياقات nonisolated (أدوار/فئات/توقّع VARA) ──
        "الدور التأهيلي الأول": "First Qualifying Round",
        "الدور التأهيلي الثاني": "Second Qualifying Round",
        "الدور التأهيلي الثالث": "Third Qualifying Round",
        "الملحق": "Play-off",
        "مرحلة الدوري": "League Stage",
        "الجولة %@ — مرحلة الدوري": "Matchday %@ — League Stage",
        "الجولة %@ — دور المجموعات": "Matchday %@ — Group Stage",
        "دور الـ%@": "Round of %@",
        "البطولات السعودية": "Saudi Competitions",
        "البطولات الخليجية": "Gulf Competitions",
        "البطولات العربية": "Arab Competitions",
        "البطولات الأوروبية": "European Competitions",
        "بطولات عالمية": "World Competitions",
        "بحسب الترتيب والفورمة": "based on standings and form",
        "بحسب الترتيب والفورمة وأفضلية الأرض": "based on standings, form, and home advantage",
        "مباراة مفتوحة بلا بيانات كافية": "an open match with limited data",
        "أفضلية الأرض فقط": "home advantage only",
        "مباراة متكافئة مرشّحة للتعادل · %@.": "An even match, likely to end in a draw · %@.",
        "مباراة متقاربة وترجيح طفيف لـ%@ · %@.": "A close match with a slight edge to %@ · %@.",
        "الأفضلية لـ%@ (%d٪) · %@.": "Edge to %@ (%d%%) · %@.",
        "التعادل هو الأرجح (%d٪) · %@.": "A draw is most likely (%d%%) · %@.",
    ]
}
