import type { Express } from "express";
import { aiHubRouter } from "./aiHub";
import systemSettingsRouter from "./systemSettings";
import adminActivityLogsRouter from "./adminActivityLogs";
import keywordFollowingRouter from "./keywordFollowing";
import interestsRouter from "./interests";
import newsMapRouter from "./newsMap";
import trendingKeywordsRouter from "./trendingKeywords";
import socialFollowingRouter from "./socialFollowing";
import liveNewsRouter from "./liveNews";
import setupRouter from "./setup";
import smartInterestsRouter from "./smartInterests";
import homepageRouter from "./homepage";
import focalPointsRouter from "./focalPoints";
import { registerTwoFactorRoutes } from "./twoFactorRoutes";
import editorPresenceRouter from "./editorPresence";
import { registerThemeRoutes } from "./themes";
import { registerStoryRoutes } from "./stories";
import { registerAbTestRoutes } from "./abTests";
import focusSessionsRouter from "./focusSessions";
import edgeMetaRouter from "./edgeMeta";
import articleEditLocksRouter from "./articleEditLocks";
import opinionTicketsRouter from "./opinionTickets";
import deployWebhooksRouter from "./deployWebhooks";
import cspReportRouter from "./cspReport";
import muqtarabOwnRouter from "./muqtarabOwn";
import muqtarabAIRouter from "./muqtarabAI";
import muqtarabWriterRouter from "./muqtarabWriter";
import { registerAnnouncementRoutes } from "./announcements";
import { registerAudioBriefRoutes } from "./audioBriefs";
import { registerShortsRoutes } from "./shorts";
import { registerCalendarRoutes } from "./calendar";
import { registerTaskRoutes } from "./tasks";
import { registerWalletRoutes } from "./wallet";
import { registerWorldCupRoutes } from "./worldCup";
import { registerAsianCupRoutes } from "./asianCup";
import { registerGulfCupRoutes } from "./gulfCup";
import { registerKingsCupRoutes } from "./kingsCup";
import { registerSportsRoutes } from "./sports";
import { registerTransferCenterRoutes } from "./transferCenter";
import { registerSportsIntelRoutes } from "./sportsIntel";
import sportsTournamentsRouter from "./sportsTournaments";
import { registerSportsLiveStreamRoutes } from "./sportsLiveStream";
import { registerRadarRoutes } from "./radar";
import { registerSpaNewsRoutes } from "./spaNews";
import { registerSportmonksNewsRoutes } from "./sportmonksNews";
import commentReactionsRouter from "./commentReactions";
import topicCommentsRouter from "./topicComments";
import wcPredictionsRouter from "./wcPredictions";
import acPredictionsRouter from "./acPredictions";
import gcPredictionsRouter from "./gcPredictions";
import rslPredictionsRouter from "./rslPredictions";
import { registerCupPredictionRoutes } from "./cupPredictions";
import mediaLibraryRouter from "./mediaLibrary";
import promptStudioRouter from "./promptStudio";
import articleViewStatsRouter from "./articleViewStats";
import keywordRouter from "./keywordRoutes";
import editorAlertsRouter from "./editorAlerts";

/**
 * Registers all route modules that were split out of the monolithic server/routes.ts.
 * Each module is a mounted Express.Router with absolute /api/... paths, so
 * behavior is identical to the original inline definitions.
 */
export function registerSplitRoutes(app: Express) {
  app.use(systemSettingsRouter);
  app.use(aiHubRouter);
  app.use(adminActivityLogsRouter);
  app.use(keywordFollowingRouter);
  app.use(interestsRouter);
  app.use(newsMapRouter);
  app.use(trendingKeywordsRouter);
  app.use(socialFollowingRouter);
  app.use(liveNewsRouter);
  app.use(setupRouter);
  app.use(smartInterestsRouter);
  app.use(homepageRouter);
  app.use(focalPointsRouter);
  registerTwoFactorRoutes(app);
  app.use(editorPresenceRouter);
  registerThemeRoutes(app);
  registerStoryRoutes(app);
  registerAbTestRoutes(app);
  app.use(focusSessionsRouter);
  app.use(edgeMetaRouter);
  app.use(articleEditLocksRouter);
  app.use(opinionTicketsRouter);
  app.use(deployWebhooksRouter);
  app.use(cspReportRouter);
  app.use(muqtarabOwnRouter);
  app.use(muqtarabAIRouter);
  app.use(muqtarabWriterRouter);
  registerAnnouncementRoutes(app);
  registerAudioBriefRoutes(app);
  registerShortsRoutes(app);
  registerCalendarRoutes(app);
  registerTaskRoutes(app);
  registerWalletRoutes(app);
  registerWorldCupRoutes(app);
  registerAsianCupRoutes(app);
  registerGulfCupRoutes(app);
  registerKingsCupRoutes(app);
  registerSportsRoutes(app);
  registerTransferCenterRoutes(app);
  registerSportsIntelRoutes(app);
  app.use(sportsTournamentsRouter);
  registerSportsLiveStreamRoutes(app);
  registerRadarRoutes(app);
  registerSpaNewsRoutes(app);
  registerSportmonksNewsRoutes(app);
  app.use(commentReactionsRouter);
  app.use(topicCommentsRouter);
  app.use(wcPredictionsRouter);
  app.use(acPredictionsRouter);
  app.use(gcPredictionsRouter);
  app.use(rslPredictionsRouter);
  registerCupPredictionRoutes(app);
  app.use(mediaLibraryRouter);
  app.use(promptStudioRouter);
  app.use(articleViewStatsRouter);
  app.use(keywordRouter);
  app.use(editorAlertsRouter);
}
