import type { Express } from "express";
import { aiHubRouter } from "./aiHub";
import { editAndGenerateStreamRouter } from "./editAndGenerateStream";
import { integrationsStatusRouter } from "./integrationsStatus";
import systemSettingsRouter from "./systemSettings";
import userDashboardThemeRouter from "./userDashboardTheme";
import adminActivityLogsRouter from "./adminActivityLogs";
import keywordFollowingRouter from "./keywordFollowing";
import interestsRouter from "./interests";
import newsMapRouter from "./newsMap";
import trendingKeywordsRouter from "./trendingKeywords";
import socialFollowingRouter from "./socialFollowing";
import liveNewsRouter from "./liveNews";
import setupRouter from "./setup";
import smartInterestsRouter from "./smartInterests";
import homepageRouter from "./homepage";
import focalPointsRouter from "./focalPoints";
import { registerTwoFactorRoutes } from "./twoFactorRoutes";
import editorPresenceRouter from "./editorPresence";
import { registerThemeRoutes } from "./themes";
import { registerStoryRoutes } from "./stories";
import { registerAbTestRoutes } from "./abTests";
import focusSessionsRouter from "./focusSessions";
import edgeMetaRouter from "./edgeMeta";
import aiPublicStatsRouter from "./aiPublicStats";
import aiStaffRouter from "./aiStaff";
import opsRoomRouter from "./opsRoom";
import articleEditLocksRouter from "./articleEditLocks";
import opinionTicketsRouter from "./opinionTickets";
import opinionAuthorWorkspaceRouter from "./opinionAuthorWorkspace";
import opinionWritersRouter from "./opinionWriters";
import authorsPublicRouter from "./authorsPublic";
import reporterMediaLicenseRouter from "./reporterMediaLicense";
import sabqPlusPreviewRouter from "./sabqPlusPreview";
import nationalDayBlockRouter from "./nationalDayBlock";
import staffProfilesRouter from "./staffProfiles";
import meetingsRouter from "./meetingsRoutes";
import meetingMinutesRouter from "./meetingMinutesRoutes";
import reportersAdminRouter from "./reportersAdmin";
import replyPolishRouter from "./replyPolish";
import deployWebhooksRouter from "./deployWebhooks";
import mailersendWebhookRouter from "./mailersendWebhook";
import cspReportRouter from "./cspReport";
import muqtarabOwnRouter from "./muqtarabOwn";
import muqtarabAIRouter from "./muqtarabAI";
import muqtarabWriterRouter from "./muqtarabWriter";
import { registerAnnouncementRoutes } from "./announcements";
import { registerShortsRoutes } from "./shorts";
import { registerCalendarRoutes } from "./calendar";
import { registerTaskRoutes } from "./tasks";
import { registerWalletRoutes } from "./wallet";
import { registerWorldCupRoutes } from "./worldCup";
import { registerAsianCupRoutes } from "./asianCup";
import { registerGulfCupRoutes } from "./gulfCup";
import { registerKingsCupRoutes } from "./kingsCup";
import { registerSportsRoutes } from "./sports";
import { registerTransferCenterRoutes } from "./transferCenter";
import { registerSportsIntelRoutes } from "./sportsIntel";
import { registerSportsSnapsRoutes } from "./sportsSnaps";
import sportsTournamentsRouter from "./sportsTournaments";
import { registerSportsLiveStreamRoutes } from "./sportsLiveStream";
import { registerEconomyRoutes } from "./economyRoutes";
import { registerRadarRoutes } from "./radar";
import { registerCoverageGapRoutes } from "./coverageGaps";
import { registerSportmonksNewsRoutes } from "./sportmonksNews";
import { registerSportsNamesRoutes } from "./sportsNames";
import commentReactionsRouter from "./commentReactions";
import topicCommentsRouter from "./topicComments";
import commentAppealsRouter from "./commentAppeals";
import topicSummaryAudioRouter from "./topicSummaryAudio";
import wcPredictionsRouter from "./wcPredictions";
import predictionsCoreRouter from "./predictionsCore";
import predictionsMobileRouter from "./predictionsMobile";
import gcMajlisRouter from "./gcMajlis";
import gcFantasyRouter from "./gcFantasy";
import rslPredictionsRouter from "./rslPredictions";
import mediaLibraryRouter from "./mediaLibrary";
import socialPublishingRouter from "./socialPublishing";
import promptStudioRouter from "./promptStudio";
import articleViewStatsRouter from "./articleViewStats";
import articleResurfaceRouter from "./articleResurface";
import articlePrClientReportRouter from "./articlePrClientReport";
import keywordRouter from "./keywordRoutes";
import editorAlertsRouter from "./editorAlerts";
import dashboardPulseRouter from "./dashboardPulse";
import adminToolsRouter from "./adminToolsRoutes";
import { systemsCatalogRouter } from "./systemsCatalog";
import surveysRouter from "./surveys";
import correspondentApplicationsRouter from "./correspondentApplications";
import promoteCorrespondentRouter from "./promoteCorrespondent";
import publisherPortalRouter from "./publisherPortal";
import smartBlocksRouter from "./smartBlocks";
import sahraaTvBlockRouter from "./sahraaTvBlock";
import wcNumbersReportRouter from "./wcNumbersReport";
import officialLettersRouter from "./officialLetters";
import accountSecurityRouter from "./accountSecurity";
import phoneRegistrationRouter from "./phoneRegistration";
import audioNewsletterCompatibilityRouter from "./audioNewsletterCompatibility";
import editorialAiRouter from "./editorialAi";
import editorialResearchRouter from "./editorialResearch";
import imageStylesRouter from "./imageStyles";
import deepseekLabRouter from "./deepseekLab";
import editorialImagesRouter from "./editorialImages";
import videoResolverRouter from "./videoResolver";

/**
 * Registers all route modules that were split out of the monolithic server/routes.ts.
 * Each module is a mounted Express.Router with absolute /api/... paths, so
 * behavior is identical to the original inline definitions.
 */
export function registerSplitRoutes(app: Express) {
  // Must run after setupAuth (caller guarantees that).
  app.use(systemSettingsRouter);
  app.use(userDashboardThemeRouter);
  app.use(aiHubRouter);
  app.use(editAndGenerateStreamRouter);
  app.use(integrationsStatusRouter);
  app.use(adminActivityLogsRouter);
  app.use(keywordFollowingRouter);
  app.use(interestsRouter);
  app.use(newsMapRouter);
  app.use(trendingKeywordsRouter);
  app.use(socialFollowingRouter);
  app.use(liveNewsRouter);
  app.use(setupRouter);
  app.use(smartInterestsRouter);
  app.use(homepageRouter);
  app.use(focalPointsRouter);
  registerTwoFactorRoutes(app);
  app.use(editorPresenceRouter);
  registerThemeRoutes(app);
  registerStoryRoutes(app);
  registerAbTestRoutes(app);
  app.use(focusSessionsRouter);
  app.use(edgeMetaRouter);
  app.use(aiPublicStatsRouter);
  app.use(aiStaffRouter);
  app.use(opsRoomRouter);
  app.use(articleEditLocksRouter);
  app.use(opinionTicketsRouter);
  app.use(opinionAuthorWorkspaceRouter);
  app.use(opinionWritersRouter);
  app.use(authorsPublicRouter);
  app.use(reporterMediaLicenseRouter);
  app.use(sabqPlusPreviewRouter);
  app.use(nationalDayBlockRouter);
  app.use(staffProfilesRouter);
  app.use(meetingsRouter);
  app.use(meetingMinutesRouter);
  app.use(reportersAdminRouter);
  app.use(replyPolishRouter);
  app.use(correspondentApplicationsRouter);
  app.use(promoteCorrespondentRouter);
  app.use(publisherPortalRouter);
  app.use(deployWebhooksRouter);
  app.use(mailersendWebhookRouter);
  app.use(cspReportRouter);
  app.use(muqtarabOwnRouter);
  app.use(muqtarabAIRouter);
  app.use(muqtarabWriterRouter);
  registerAnnouncementRoutes(app);
  registerShortsRoutes(app);
  registerCalendarRoutes(app);
  registerTaskRoutes(app);
  registerWalletRoutes(app);
  registerWorldCupRoutes(app);
  registerAsianCupRoutes(app);
  registerGulfCupRoutes(app);
  registerKingsCupRoutes(app);
  registerSportsRoutes(app);
  registerTransferCenterRoutes(app);
  registerSportsIntelRoutes(app);
  registerSportsSnapsRoutes(app);
  app.use(sportsTournamentsRouter);
  registerSportsLiveStreamRoutes(app);
  // اقتصاد سبق الحي — بيانات ساما + SSE
  registerEconomyRoutes(app);
  registerRadarRoutes(app);
  registerCoverageGapRoutes(app);
  registerSportmonksNewsRoutes(app);
  registerSportsNamesRoutes(app);
  app.use(commentReactionsRouter);
  app.use(topicCommentsRouter);
  app.use(commentAppealsRouter);
  app.use(topicSummaryAudioRouter);
  app.use(wcPredictionsRouter);
  app.use(predictionsCoreRouter);
  app.use(predictionsMobileRouter);
  app.use(gcMajlisRouter);
  app.use(gcFantasyRouter);
  app.use(rslPredictionsRouter);
  app.use(mediaLibraryRouter);
  app.use(socialPublishingRouter);
  app.use(promptStudioRouter);
  app.use(articleViewStatsRouter);
  app.use(articleResurfaceRouter);
  app.use(articlePrClientReportRouter);
  app.use(keywordRouter);
  app.use(editorAlertsRouter);
  app.use(dashboardPulseRouter);
  app.use(adminToolsRouter);
  app.use(systemsCatalogRouter);
  app.use(surveysRouter);
  // Smart Blocks / Homepage Stage — قبل معالجات routes.ts القديمة لنفس المسارات
  app.use(smartBlocksRouter);
  app.use("/api/sahraa-tv-block", sahraaTvBlockRouter);
  app.use(wcNumbersReportRouter);
  app.use(accountSecurityRouter);
  app.use(officialLettersRouter);
  // إكمال تسجيل عضوية الجوال + استكمال الحسابات القديمة (auth-rbac)
  app.use(phoneRegistrationRouter);
  app.use(audioNewsletterCompatibilityRouter);
  // نظام التحرير الموحد «محرر سبق» (docs/editorial-ai-unified-system-plan-2026-08-03.md)
  app.use(editorialAiRouter);
  app.use(editorialResearchRouter);
  // أنماط توليد الصور (editorial)
  app.use(imageStylesRouter);
  app.use(deepseekLabRouter);
  app.use(editorialImagesRouter);
  // معالج استخراج ومعاينة روابط الفيديو (YouTube, Dailymotion, X/Twitter)
  app.use(videoResolverRouter);
}
