export interface TopicHubSpec {
  key: string;
  nameAr: string;
  nameEn: string;
  slug: string;
  description: string;
  minPublishedArticles: number;
  maxLinksPerArticle?: number;
  includeAny: string[];
  includeAll?: string[];
  excludeAny?: string[];
}

export const TOPIC_HUBS: TopicHubSpec[] = [
  {
    key: "weather",
    nameAr: "الطقس",
    nameEn: "Weather",
    slug: "الطقس",
    description: "تغطية مستمرة لأخبار الطقس والأرصاد والحالة الجوية في السعودية.",
    minPublishedArticles: 5,
    includeAny: [
      "الطقس",
      "الأرصاد",
      "الحالة الجوية",
      "أمطار",
      "رياح",
      "غبار",
      "أتربة",
      "حرارة",
      "درجات الحرارة",
      "سيول",
      "إنذار أحمر",
      "إنذار برتقالي",
    ],
    excludeAny: ["حالة الطقس في لعبة", "تطبيق الطقس"],
  },
  {
    key: "hajj",
    nameAr: "الحج",
    nameEn: "Hajj",
    slug: "الحج",
    description: "أخبار الحج وخدمات ضيوف الرحمن والجهات المشاركة في موسم الحج.",
    minPublishedArticles: 5,
    includeAny: [
      "الحج",
      "حجاج",
      "ضيوف الرحمن",
      "المشاعر المقدسة",
      "منى",
      "عرفات",
      "مزدلفة",
      "المسجد الحرام",
      "موسم حج",
      "مناسك الحج",
    ],
  },
  {
    key: "education",
    nameAr: "التعليم",
    nameEn: "Education",
    slug: "التعليم",
    description: "أخبار التعليم والمدارس والجامعات والاختبارات في السعودية.",
    minPublishedArticles: 5,
    includeAny: [
      "التعليم",
      "وزارة التعليم",
      "المدارس",
      "الطلاب",
      "الطالبات",
      "المعلمين",
      "المعلمات",
      "الجامعات",
      "الاختبارات",
      "التقويم الدراسي",
    ],
  },
  {
    key: "jobs",
    nameAr: "الوظائف",
    nameEn: "Jobs",
    slug: "الوظائف",
    description: "أخبار الوظائف والتوظيف وفرص العمل والموارد البشرية في السعودية.",
    minPublishedArticles: 5,
    includeAny: [
      "وظائف",
      "الوظائف",
      "توظيف",
      "فرص عمل",
      "الموارد البشرية",
      "سوق العمل",
      "العمل عن بعد",
      "ساعات العمل",
      "نظام العمل",
    ],
  },
  {
    key: "citizen-account",
    nameAr: "حساب المواطن",
    nameEn: "Citizen Account",
    slug: "حساب-المواطن",
    description: "أخبار برنامج حساب المواطن والدعم والأهلية ومواعيد الصرف.",
    minPublishedArticles: 5,
    includeAny: [
      "حساب المواطن",
      "برنامج حساب المواطن",
      "الدعم",
      "الأهلية",
      "دفعة حساب المواطن",
      "مستفيدي حساب المواطن",
    ],
  },
  {
    key: "saudi-sports",
    nameAr: "الرياضة السعودية",
    nameEn: "Saudi Sports",
    slug: "الرياضة-السعودية",
    description: "أخبار الرياضة السعودية والمنتخبات والأندية والمسابقات المحلية.",
    minPublishedArticles: 5,
    includeAny: [
      "الرياضة السعودية",
      "المنتخب السعودي",
      "الأخضر",
      "الدوري السعودي",
      "دوري روشن",
      "الهلال",
      "النصر",
      "الاتحاد",
      "الأهلي",
      "كأس الملك",
    ],
  },
  {
    key: "traffic",
    nameAr: "المرور",
    nameEn: "Traffic",
    slug: "المرور",
    description: "أخبار المرور والسلامة المرورية والتنقل والطرق في السعودية.",
    minPublishedArticles: 5,
    includeAny: [
      "المرور",
      "السلامة المرورية",
      "الحركة المرورية",
      "الازدحام",
      "الطرق",
      "النقل",
      "المخالفات المرورية",
      "الحوادث المرورية",
    ],
  },
  {
    key: "health",
    nameAr: "الصحة",
    nameEn: "Health",
    slug: "الصحة",
    description: "أخبار الصحة والوقاية والخدمات الصحية في السعودية والعالم.",
    minPublishedArticles: 5,
    includeAny: [
      "الصحة",
      "وزارة الصحة",
      "الوقاية",
      "المستشفيات",
      "الأطباء",
      "السكري",
      "الصحة العالمية",
      "القطاع الصحي",
      "الخدمات الصحية",
    ],
  },
  {
    key: "saudi-economy",
    nameAr: "الاقتصاد السعودي",
    nameEn: "Saudi Economy",
    slug: "الاقتصاد-السعودي",
    description: "أخبار الاقتصاد السعودي والأسواق والاستثمار والشركات.",
    minPublishedArticles: 5,
    includeAny: [
      "الاقتصاد السعودي",
      "السوق المالية",
      "تداول",
      "الاستثمار",
      "الناتج المحلي",
      "النفط",
      "الشركات السعودية",
      "رؤية 2030",
      "القطاع الخاص",
    ],
  },
  {
    key: "artificial-intelligence",
    nameAr: "الذكاء الاصطناعي",
    nameEn: "Artificial Intelligence",
    slug: "الذكاء-الاصطناعي",
    description: "أخبار الذكاء الاصطناعي والتقنيات الناشئة وتطبيقاتها.",
    minPublishedArticles: 5,
    includeAny: [
      "الذكاء الاصطناعي",
      "ذكاء اصطناعي",
      "تقنيات الذكاء",
      "النماذج اللغوية",
      "تعلم الآلة",
      "البيانات",
      "تقنية",
    ],
  },
];
