export interface TopicHubSpec {
  key: string;
  nameAr: string;
  nameEn: string;
  slug: string;
  description: string;
  minPublishedArticles: number;
  minScore?: number;
  maxLinksPerArticle?: number;
  anchorAny?: string[];
  includeAny: string[];
  includeAll?: string[];
  excludeAny?: string[];
}

export const TOPIC_HUBS: TopicHubSpec[] = [
  {
    key: "weather",
    nameAr: "الطقس",
    nameEn: "Weather",
    slug: "الطقس",
    description: "تغطية مستمرة لأخبار الطقس والأرصاد والحالة الجوية في السعودية.",
    minPublishedArticles: 5,
    minScore: 2,
    anchorAny: ["الطقس", "الأرصاد", "الحالة الجوية"],
    includeAny: [
      "الطقس",
      "الأرصاد",
      "الحالة الجوية",
      "أمطار",
      "رياح",
      "غبار",
      "أتربة",
      "حرارة",
      "درجات الحرارة",
      "سيول",
      "إنذار أحمر",
      "إنذار برتقالي",
    ],
    excludeAny: ["حالة الطقس في لعبة", "تطبيق الطقس"],
  },
  {
    key: "hajj",
    nameAr: "الحج",
    nameEn: "Hajj",
    slug: "الحج",
    description: "أخبار الحج وخدمات ضيوف الرحمن والجهات المشاركة في موسم الحج.",
    minPublishedArticles: 5,
    minScore: 2,
    anchorAny: ["الحج", "حجاج", "ضيوف الرحمن", "موسم حج", "مناسك الحج"],
    includeAny: [
      "الحج",
      "حجاج",
      "ضيوف الرحمن",
      "المشاعر المقدسة",
      "منى",
      "عرفات",
      "مزدلفة",
      "المسجد الحرام",
      "موسم حج",
      "مناسك الحج",
    ],
  },
  {
    key: "education",
    nameAr: "التعليم",
    nameEn: "Education",
    slug: "التعليم",
    description: "أخبار التعليم والمدارس والجامعات والاختبارات في السعودية.",
    minPublishedArticles: 5,
    minScore: 2,
    anchorAny: ["التعليم", "وزارة التعليم", "المدارس", "الجامعات", "التقويم الدراسي"],
    includeAny: [
      "التعليم",
      "وزارة التعليم",
      "المدارس",
      "الطلاب",
      "الطالبات",
      "المعلمين",
      "المعلمات",
      "الجامعات",
      "الاختبارات",
      "التقويم الدراسي",
    ],
  },
  {
    key: "jobs",
    nameAr: "الوظائف",
    nameEn: "Jobs",
    slug: "الوظائف",
    description: "أخبار الوظائف والتوظيف وفرص العمل والموارد البشرية في السعودية.",
    minPublishedArticles: 5,
    minScore: 2,
    anchorAny: ["وظائف", "الوظائف", "توظيف", "فرص عمل", "سوق العمل"],
    includeAny: [
      "وظائف",
      "الوظائف",
      "توظيف",
      "فرص عمل",
      "الموارد البشرية",
      "سوق العمل",
      "العمل عن بعد",
      "ساعات العمل",
      "نظام العمل",
    ],
  },
  {
    key: "citizen-account",
    nameAr: "حساب المواطن",
    nameEn: "Citizen Account",
    slug: "حساب-المواطن",
    description: "أخبار برنامج حساب المواطن والدعم والأهلية ومواعيد الصرف.",
    minPublishedArticles: 5,
    minScore: 1,
    anchorAny: ["حساب المواطن", "برنامج حساب المواطن"],
    includeAny: [
      "حساب المواطن",
      "برنامج حساب المواطن",
      "دفعة حساب المواطن",
      "مستفيدي حساب المواطن",
      "أهلية حساب المواطن",
      "دعم حساب المواطن",
    ],
  },
  {
    key: "saudi-sports",
    nameAr: "الرياضة السعودية",
    nameEn: "Saudi Sports",
    slug: "الرياضة-السعودية",
    description: "أخبار الرياضة السعودية والمنتخبات والأندية والمسابقات المحلية.",
    minPublishedArticles: 5,
    minScore: 2,
    anchorAny: ["الرياضة السعودية", "المنتخب السعودي", "الدوري السعودي", "دوري روشن"],
    includeAny: [
      "الرياضة السعودية",
      "المنتخب السعودي",
      "الأخضر",
      "الدوري السعودي",
      "دوري روشن",
      "الهلال",
      "النصر",
      "نادي الاتحاد",
      "الأهلي",
      "كأس الملك",
    ],
  },
  {
    key: "traffic",
    nameAr: "المرور",
    nameEn: "Traffic",
    slug: "المرور",
    description: "أخبار المرور والسلامة المرورية والتنقل والطرق في السعودية.",
    minPublishedArticles: 5,
    minScore: 2,
    anchorAny: ["المرور", "السلامة المرورية", "الحركة المرورية", "المخالفات المرورية"],
    includeAny: [
      "المرور",
      "السلامة المرورية",
      "الحركة المرورية",
      "الازدحام",
      "الطرق",
      "المخالفات المرورية",
      "الحوادث المرورية",
    ],
  },
  {
    key: "health",
    nameAr: "الصحة",
    nameEn: "Health",
    slug: "الصحة",
    description: "أخبار الصحة والوقاية والخدمات الصحية في السعودية والعالم.",
    minPublishedArticles: 5,
    minScore: 2,
    anchorAny: ["الصحة", "وزارة الصحة", "الصحة العالمية", "القطاع الصحي", "الخدمات الصحية"],
    includeAny: [
      "الصحة",
      "وزارة الصحة",
      "الوقاية",
      "المستشفيات",
      "الأطباء",
      "السكري",
      "الصحة العالمية",
      "القطاع الصحي",
      "الخدمات الصحية",
    ],
  },
  {
    key: "saudi-economy",
    nameAr: "الاقتصاد السعودي",
    nameEn: "Saudi Economy",
    slug: "الاقتصاد-السعودي",
    description: "أخبار الاقتصاد السعودي والأسواق والاستثمار والشركات.",
    minPublishedArticles: 5,
    minScore: 2,
    anchorAny: ["الاقتصاد السعودي", "السوق المالية", "سوق الأسهم", "أسعار النفط"],
    includeAny: [
      "الاقتصاد السعودي",
      "السوق المالية",
      "تداول",
      "الاستثمار",
      "الناتج المحلي",
      "النفط",
      "الشركات السعودية",
      "رؤية 2030",
      "القطاع الخاص",
      "أسعار النفط",
      "سوق الأسهم",
    ],
  },
  {
    key: "artificial-intelligence",
    nameAr: "الذكاء الاصطناعي",
    nameEn: "Artificial Intelligence",
    slug: "الذكاء-الاصطناعي",
    description: "أخبار الذكاء الاصطناعي والتقنيات الناشئة وتطبيقاتها.",
    minPublishedArticles: 5,
    minScore: 2,
    anchorAny: ["الذكاء الاصطناعي", "ذكاء اصطناعي", "تقنيات الذكاء"],
    includeAny: [
      "الذكاء الاصطناعي",
      "ذكاء اصطناعي",
      "تقنيات الذكاء",
      "النماذج اللغوية",
      "تعلم الآلة",
      "بيانات الذكاء الاصطناعي",
      "تقنيات ناشئة",
    ],
  },
];
