import {
  LayoutDashboard,
  FileText,
  FolderOpen,
  Users,
  PlusCircle,
  Shield,
  Palette,
  Rss,
  MessageSquare,
  Tag,
  Sparkles,
  AudioLines,
  Brain,
  Type,
  ShieldCheck,
  KeyRound,
  UserCircle,
  SquareStack,
  PieChart,
  Activity,
  MousePointer,
  SplitSquareHorizontal,
  FlaskConical,
  Settings,
  Plug,
  Cloud,
  ListChecks,
  Newspaper,
  User,
  Flame,
  Boxes,
  Lightbulb,
  Target,
  Telescope,
  Grid3x3,
  Podcast,
  Megaphone,
  BookOpen,
  Calendar,
  Link,
  ImageIcon,
  LayoutGrid,
  MapPin,
  Wand2,
  BarChart,
  ListTodo,
  Globe,
  Mail,
  Building2,
  FileCheck,
  DollarSign,
  CreditCard,
  Store,
  Bell,
  PenLine,
  TrendingUp,
  Mic,
  FileAudio,
  Wrench,
} from "lucide-react";
import type { NavItem } from "./types";

/**
 * مصدر الحقيقة الواحد لجميع عناصر القائمة الجانبية
 * Single Source of Truth for all navigation items
 */
export const navConfig: NavItem[] = [
  {
    id: "dashboard",
    labelKey: "nav.dashboard",
    labelAr: "نظرة عامة",
    path: "/dashboard",
    icon: LayoutDashboard,
    roles: ["admin", "editor", "author", "reviewer", "analyst", "reporter", "comments_moderator", "guest", "opinion_author"],
    // No permissions - all authenticated users can access the dashboard overview
    meta: { exact: true },
  },

  // ===== كاتب الرأي / Opinion Author =====
  {
    id: "opinion_author_section",
    labelKey: "nav.my_articles",
    labelAr: "مقالاتي",
    icon: PenLine,
    roles: ["opinion_author"],
    children: [
      {
        id: "opinion_author_dashboard",
        labelKey: "nav.opinion_dashboard",
        labelAr: "لوحة التحكم",
        path: "/dashboard/opinion-author",
        icon: LayoutDashboard,
        roles: ["opinion_author"],
      },
      {
        id: "opinion_author_new_article",
        labelKey: "nav.new_article",
        labelAr: "مقال جديد",
        path: "/dashboard/articles/new",
        icon: PlusCircle,
        roles: ["opinion_author"],
      },
    ],
  },

  // ===== الناشر / Publisher Staff =====
  {
    id: "publisher_section",
    labelKey: "nav.publisher_dashboard",
    labelAr: "لوحة الناشر",
    icon: Building2,
    roles: ["publisher"],
    children: [
      {
        id: "publisher_overview",
        labelKey: "nav.publisher_overview",
        labelAr: "نظرة عامة",
        path: "/dashboard/publisher",
        icon: LayoutDashboard,
        roles: ["publisher"],
      },
      {
        id: "publisher_articles",
        labelKey: "nav.publisher_articles",
        labelAr: "مقالاتي",
        path: "/dashboard/publisher/articles",
        icon: FileText,
        roles: ["publisher"],
      },
      {
        id: "publisher_new_article",
        labelKey: "nav.publisher_new_article",
        labelAr: "مقال جديد",
        path: "/dashboard/publisher/article/new",
        icon: PlusCircle,
        roles: ["publisher"],
      },
      {
        id: "publisher_credits",
        labelKey: "nav.publisher_credits",
        labelAr: "رصيد النشر",
        path: "/dashboard/publisher/credits",
        icon: CreditCard,
        roles: ["publisher"],
      },
    ],
  },

  // ===== مركز المهام / Tasks Center =====
  {
    id: "tasks",
    labelKey: "nav.tasks",
    labelAr: "مركز المهام",
    path: "/dashboard/tasks",
    icon: ListTodo,
    roles: ["admin", "editor", "author", "reviewer", "analyst", "reporter"],
    permissions: ["tasks.view_all", "tasks.view_own", "tasks.create"],
  },

  // ===== المحتوى / Content =====
  {
    id: "content",
    labelKey: "nav.content",
    labelAr: "المحتوى",
    icon: Newspaper,
    roles: ["admin", "editor", "author", "reviewer", "comments_moderator", "reporter"],
    // No parent permissions - each child validates independently and parent shows if any child is accessible
    children: [
      {
        id: "articles",
        labelKey: "nav.articles",
        labelAr: "الأخبار والمقالات",
        path: "/dashboard/articles",
        icon: FileText,
        roles: ["admin", "editor", "author", "reviewer", "reporter"],
        permissions: ["articles.view"], // Users with articles.view permission can access
      },
      {
        id: "new_article",
        labelKey: "nav.new_article",
        labelAr: "مقال جديد",
        path: "/dashboard/articles/new",
        icon: PlusCircle,
        roles: ["admin", "editor", "author", "reporter"],
        permissions: ["articles.create"], // Users with articles.create permission can access
      },
      {
        id: "push_notifications",
        labelKey: "nav.push_notifications",
        labelAr: "الإشعارات",
        path: "/dashboard/push-notifications",
        icon: Bell,
        roles: ["admin"],
      },
      {
        id: "foreign_news",
        labelKey: "nav.foreign_news",
        labelAr: "رصد الأخبار الأجنبية",
        path: "/dashboard/foreign-news",
        icon: Globe,
        roles: ["admin", "editor"],
      },
      {
        id: "categories",
        labelKey: "nav.categories",
        labelAr: "التصنيفات",
        path: "/dashboard/categories",
        icon: FolderOpen,
        roles: ["admin", "editor"],
        permissions: ["categories.view", "categories.create", "categories.update"],
      },
      {
        id: "tags",
        labelKey: "nav.tags",
        labelAr: "الوسوم",
        path: "/dashboard/tags",
        icon: Tag,
        roles: ["admin", "editor"],
        permissions: ["tags.view", "tags.manage"],
      },
      {
        id: "smart_links",
        labelKey: "nav.smart_links",
        labelAr: "الروابط الذكية",
        path: "/dashboard/smart-links",
        icon: Link,
        roles: ["admin", "editor"],
        permissions: ["smart_links.view", "smart_links.manage"],
      },
      {
        id: "gulf_events",
        labelKey: "nav.gulf_events",
        labelAr: "البث الحي — الاعتداءات",
        path: "/dashboard/gulf-events",
        icon: Shield,
        roles: ["admin", "editor", "content_manager"],
      },
      {
        id: "breaking_ticker",
        labelKey: "nav.breaking_ticker",
        labelAr: "شريط الأخبار العاجلة",
        path: "/dashboard/breaking-ticker",
        icon: Flame,
        roles: ["admin", "editor"],
        permissions: ["breaking_ticker.manage"],
      },
      {
        id: "ai_moderation",
        labelKey: "nav.ai_moderation",
        labelAr: "الرقابة الذكية",
        path: "/dashboard/ai-moderation",
        icon: ShieldCheck,
        roles: ["admin", "comments_moderator"],
        permissions: ["comments.view", "comments.approve", "comments.reject", "comments.delete"],
      },
      {
        id: "muqtarab",
        labelKey: "nav.muqtarab",
        labelAr: "مُقترب",
        path: "/dashboard/muqtarab",
        icon: Boxes,
        roles: ["admin", "editor"],
        permissions: ["muqtarab.manage", "muqtarab.publish"],
      },
      {
        id: "mirqab",
        labelKey: "nav.mirqab",
        labelAr: "المرقاب",
        path: "/dashboard/mirqab",
        icon: Telescope,
        roles: ["admin", "editor"],
        permissions: ["mirqab.view", "mirqab.create", "mirqab.edit", "mirqab.publish"],
      },
      {
        id: "foreign_news",
        labelKey: "nav.foreign_news",
        labelAr: "رصد الأخبار الأجنبية",
        path: "/dashboard/foreign-news",
        icon: Globe,
        roles: ["admin", "editor"],
        permissions: ["foreign_news.view", "foreign_news.manage"],
      },
      {
        id: "audio_newsletters",
        labelKey: "nav.audio_newsletters",
        labelAr: "النشرات الصوتية",
        path: "/dashboard/audio-newsletters",
        icon: Podcast,
        roles: ["admin", "editor"],
        permissions: ["audio.view", "audio.manage", "newsletters.view"],
      },
      {
        id: "audio_briefs",
        labelKey: "nav.audio_briefs",
        labelAr: "الأخبار الصوتية السريعة",
        path: "/dashboard/audio-briefs",
        icon: AudioLines,
        roles: ["admin", "editor"],
        permissions: ["audio.view", "audio.manage"],
      },
      {
        id: "calendar",
        labelKey: "nav.calendar",
        labelAr: "تقويم سبق",
        path: "/dashboard/calendar",
        icon: Calendar,
        roles: ["admin", "editor"],
        permissions: ["calendar:view", "calendar:create", "calendar:edit"],
      },
      {
        id: "world_days",
        labelKey: "nav.world_days",
        labelAr: "الأيام العالمية",
        path: "/dashboard/world-days",
        icon: Globe,
        roles: ["admin", "editor"],
      },
      {
        id: "media_library",
        labelKey: "nav.media_library",
        labelAr: "مكتبة الوسائط",
        path: "/dashboard/media-library",
        icon: ImageIcon,
        roles: ["admin", "editor", "author"],
        excludeRoles: ["opinion_author", "reporter"],
        permissions: ["media.view", "media.upload"],
      },
    ],
  },

  // ===== المتجر الإعلامي / Media Store =====
  {
    id: "media_store",
    labelKey: "nav.media_store",
    labelAr: "المتجر الإعلامي",
    icon: Store,
    roles: ["admin"],
    children: [
      {
        id: "media_store_orders",
        labelKey: "nav.media_store_orders",
        labelAr: "إدارة الطلبات",
        path: "/dashboard/media-store-orders",
        icon: FileCheck,
        roles: ["admin"],
      },
      {
        id: "native_ads",
        labelKey: "nav.native_ads",
        labelAr: "المحتوى المدفوع",
        path: "/dashboard/native-ads",
        icon: DollarSign,
        roles: ["admin"],
      },
      {
        id: "payment-analytics",
        labelKey: "nav.payment_analytics",
        labelAr: "تحليلات المدفوعات",
        path: "/dashboard/payment-analytics",
        icon: CreditCard,
        roles: ["admin"],
      },
    ],
  },

  // ===== رسائل التواصل / Contact Messages =====
  {
    id: "contact_messages",
    labelKey: "nav.contact_messages",
    labelAr: "رسائل التواصل",
    path: "/dashboard/contact-messages",
    icon: MessageSquare,
    roles: ["admin", "editor"],
  },

  // ===== الإعلانات / Advertising =====
  {
    id: "advertising",
    labelKey: "nav.advertising",
    labelAr: "الإعلانات",
    icon: Megaphone,
    roles: ["admin", "advertiser"],
    children: [
      {
        id: "ad_campaigns",
        labelKey: "nav.campaigns",
        labelAr: "الحملات الإعلانية",
        path: "/dashboard/ads/campaigns",
        icon: Megaphone,
        roles: ["admin", "advertiser"],
        permissions: ["ads.view", "ads.manage"],
      },
      {
        id: "ad_creatives",
        labelKey: "nav.creatives",
        labelAr: "البنرات الإعلانية",
        path: "/dashboard/ads/creatives",
        icon: ImageIcon,
        roles: ["admin", "advertiser"],
        permissions: ["ads.view", "ads.manage"],
      },
      {
        id: "inventory_slots",
        labelKey: "nav.inventory_slots",
        labelAr: "أماكن الظهور",
        path: "/dashboard/ads/inventory-slots",
        icon: MapPin,
        roles: ["admin", "advertiser"],
        permissions: ["ads.view", "ads.manage"],
      },
      {
        id: "ad_account",
        labelKey: "nav.ad_account",
        labelAr: "حسابي الإعلاني",
        path: "/dashboard/ads/account",
        icon: User,
        roles: ["admin", "advertiser"],
        permissions: ["ads.view", "ads.account"],
      },
      {
        id: "ad_analytics",
        labelKey: "nav.ad_analytics",
        labelAr: "تحليلات الإعلانات",
        path: "/dashboard/ads/analytics",
        icon: BarChart,
        roles: ["admin", "advertiser"],
        permissions: ["ads.view"],
      },
    ],
  },

  // ===== التحليل العميق / Deep Analysis =====
  {
    id: "deep_analysis",
    labelKey: "nav.deep_analysis",
    labelAr: "التحليل العميق",
    icon: Brain,
    roles: ["admin", "editor", "analyst"],
    children: [
      {
        id: "deep_analysis_manage",
        labelKey: "nav.deep_analysis_manage",
        labelAr: "إدارة التحليلات",
        path: "/dashboard/ai/deep-analysis-list",
        icon: LayoutGrid,
        roles: ["admin", "editor", "analyst"],
        permissions: ["analysis.view", "analysis.manage"],
      },
      {
        id: "deep_analysis_create",
        labelKey: "nav.deep_analysis_create",
        labelAr: "إنشاء تحليل جديد",
        path: "/dashboard/ai/deep",
        icon: Brain,
        roles: ["admin", "analyst"],
        permissions: ["analysis.create", "analysis.manage"],
      },
      {
        id: "deep_analysis_public",
        labelKey: "nav.deep_analysis_public",
        labelAr: "التحليلات المنشورة",
        path: "/omq",
        icon: Globe,
        roles: ["admin", "editor", "analyst"],
        permissions: ["analysis.view"],
      },
      {
        id: "deep_analysis_stats",
        labelKey: "nav.deep_analysis_stats",
        labelAr: "الإحصائيات والتقارير",
        path: "/omq/stats",
        icon: BarChart,
        roles: ["admin", "analyst"],
        permissions: ["analysis.view", "analytics.view"],
      },
    ],
  },

  // ===== الذكاء الاصطناعي / AI =====
  {
    id: "ai",
    labelKey: "nav.ai",
    labelAr: "الذكاء الاصطناعي",
    icon: Sparkles,
    roles: ["admin", "editor", "analyst"],
    featureFlags: ["aiDeepAnalysis"],
    children: [
      {
        id: "ai_summaries",
        labelKey: "nav.ai_summaries",
        labelAr: "الملخصات الصوتية",
        path: "/dashboard/ai/summaries",
        icon: AudioLines,
        roles: ["admin", "editor"],
        permissions: ["ai.view", "ai.manage"],
      },
      {
        id: "ai_headlines",
        labelKey: "nav.ai_headlines",
        labelAr: "العناوين الذكية",
        path: "/dashboard/ai/headlines",
        icon: Type,
        roles: ["admin", "editor"],
        permissions: ["ai.view", "ai.manage"],
      },
    ],
  },

  // ===== الأدوات الذكية / Smart Tools =====
  {
    id: "smart_tools",
    labelKey: "nav.smart_tools",
    labelAr: "الأدوات الذكية",
    icon: Wand2,
    roles: ["admin", "editor"],
    children: [
      {
        id: "smart_journalist",
        labelKey: "nav.smart_journalist",
        labelAr: "الوكيل الصحفي الذكي",
        path: "/dashboard/smart-journalist",
        icon: Brain,
        roles: ["admin", "editor"],
        permissions: ["ai.view", "ai.manage", "tools.view"],
      },
      {
        id: "ai_tools",
        labelKey: "nav.ai_tools",
        labelAr: "مركز الذكاء الاصطناعي",
        path: "/dashboard/ai-tools",
        icon: Sparkles,
        roles: ["admin", "editor"],
        permissions: ["ai.view", "ai.manage", "tools.view"],
      },
      {
        id: "data_story_generator",
        labelKey: "nav.data_story_generator",
        labelAr: "صحافة البيانات",
        path: "/dashboard/data-stories",
        icon: BarChart,
        roles: ["admin", "editor"],
        permissions: ["ai.view", "tools.view"],
      },
      {
        id: "voice_management",
        labelKey: "nav.voice_management",
        labelAr: "إدارة الأصوات",
        path: "/dashboard/voice-management",
        icon: Mic,
        roles: ["admin", "superadmin", "super_admin", "system_admin"],
        permissions: ["ai.manage"],
      },
      {
        id: "transcription_tool",
        labelKey: "nav.transcription_tool",
        labelAr: "تفريغ المقاطع",
        path: "/dashboard/transcription-tool",
        icon: FileAudio,
        roles: ["admin", "superadmin", "super_admin", "system_admin", "editor", "author", "reporter"],
        permissions: ["ai.view", "tools.view"],
      },
    ],
  },

  // ===== المستخدمون والأدوار / Users & Roles =====
  {
    id: "users",
    labelKey: "nav.users_and_roles",
    labelAr: "المستخدمون والأدوار",
    icon: Users,
    roles: ["admin"],
    children: [
      {
        id: "staff",
        labelKey: "nav.staff",
        labelAr: "منسوبي سبق",
        path: "/dashboard/staff",
        icon: Shield,
        roles: ["admin"],
        permissions: ["users.view", "users.manage"],
      },
      {
        id: "users_mgmt",
        labelKey: "nav.users",
        labelAr: "القرّاء",
        path: "/dashboard/users",
        icon: UserCircle,
        roles: ["admin"],
        permissions: ["users.view", "users.manage"],
      },
      {
        id: "roles",
        labelKey: "nav.roles",
        labelAr: "الأدوار والصلاحيات",
        path: "/dashboard/roles",
        icon: ShieldCheck,
        roles: ["admin"],
        permissions: ["roles.view", "roles.manage"],
      },
      {
        id: "permissions",
        labelKey: "nav.permissions",
        labelAr: "الصلاحيات",
        path: "/dashboard/permissions",
        icon: KeyRound,
        roles: ["admin"],
        permissions: ["permissions.view", "permissions.manage"],
      },
      {
        id: "correspondents",
        labelKey: "nav.correspondents",
        labelAr: "طلبات المراسلين",
        path: "/dashboard/correspondents",
        icon: User,
        roles: ["admin"],
        permissions: ["users.view", "users.manage"],
      },
      {
        id: "opinion-authors",
        labelKey: "nav.opinionAuthors",
        labelAr: "طلبات كتّاب الرأي",
        path: "/dashboard/opinion-author-applications",
        icon: BookOpen,
        roles: ["admin"],
        permissions: ["users.view", "users.manage"],
      },
      {
        id: "email-templates",
        labelKey: "nav.emailTemplates",
        labelAr: "قوالب البريد الإلكتروني",
        path: "/dashboard/email-templates",
        icon: Mail,
        roles: ["admin"],
        permissions: ["users.manage"],
      },
      {
        id: "staff-communications",
        labelKey: "nav.staffCommunications",
        labelAr: "راسل الزملاء",
        path: "/dashboard/staff-communications",
        icon: MessageSquare,
        roles: ["admin"],
        permissions: ["communications.staff"],
      },
      {
        id: "staff-productivity",
        labelKey: "nav.staffProductivity",
        labelAr: "إنتاجية الموظفين",
        path: "/dashboard/productivity",
        icon: TrendingUp,
        roles: ["admin"],
        permissions: ["staff.view_productivity"],
      },
    ],
  },

  // ===== الناشرون والوكالات / Publishers & Agencies =====
  {
    id: "publishers",
    labelKey: "nav.publishers",
    labelAr: "الناشرون والوكالات",
    icon: Building2,
    roles: ["admin"],
    children: [
      {
        id: "publishers_list",
        labelKey: "nav.publishers_list",
        labelAr: "قائمة الناشرين",
        path: "/dashboard/admin/publishers",
        icon: Building2,
        roles: ["admin"],
        permissions: ["publishers.view", "publishers.manage"],
      },
      {
        id: "publishers_articles",
        labelKey: "nav.publishers_articles",
        labelAr: "مراجعة المقالات",
        path: "/dashboard/admin/publisher-articles",
        icon: FileCheck,
        roles: ["admin"],
        permissions: ["publishers.view", "articles.review"],
      },
      {
        id: "publishers_analytics",
        labelKey: "nav.publishers_analytics",
        labelAr: "التحليلات والإحصائيات",
        path: "/dashboard/admin/publisher-analytics",
        icon: BarChart,
        roles: ["admin"],
        permissions: ["publishers.view", "analytics.view"],
      },
    ],
  },

  // ===== المظهر / Appearance =====
  {
    id: "appearance",
    labelKey: "nav.appearance",
    labelAr: "المظهر",
    icon: Palette,
    roles: ["admin", "editor"],
    featureFlags: ["smartThemes"],
    children: [
      {
        id: "themes",
        labelKey: "nav.themes",
        labelAr: "السمات",
        path: "/dashboard/themes",
        icon: Palette,
        roles: ["admin", "editor"],
        permissions: ["appearance.view", "appearance.manage"],
      },
      {
        id: "templates",
        labelKey: "nav.templates",
        labelAr: "القوالب",
        path: "/dashboard/templates",
        icon: SquareStack,
        roles: ["admin", "editor"],
        permissions: ["appearance.view", "templates.manage"],
      },
    ],
  },

  // ===== التحليلات / Analytics =====
  {
    id: "analytics",
    labelKey: "nav.analytics",
    labelAr: "التحليلات",
    icon: PieChart,
    roles: ["admin", "analyst"],
    excludeRoles: ["reporter"],
    children: [
      {
        id: "dashboards",
        labelKey: "nav.analytics_dashboards",
        labelAr: "لوحات التحليلات",
        path: "/dashboard/analytics",
        icon: Activity,
        roles: ["admin", "analyst"],
        permissions: ["analytics.view"],
      },
      {
        id: "trending",
        labelKey: "nav.trending",
        labelAr: "الرائج",
        path: "/dashboard/analytics/trending",
        icon: Flame,
        roles: ["admin", "analyst"],
        permissions: ["analytics.view"],
      },
      {
        id: "behavior",
        labelKey: "nav.user_behavior",
        labelAr: "سلوك المستخدمين",
        path: "/dashboard/analytics/behavior",
        icon: MousePointer,
        roles: ["admin", "analyst"],
        permissions: ["analytics.view", "analytics.behavior"],
      },
      {
        id: "abTests",
        labelKey: "nav.ab_tests",
        labelAr: "اختبارات A/B",
        path: "/dashboard/analytics/ab-tests",
        icon: FlaskConical,
        roles: ["admin", "editor", "analyst"],
        permissions: ["analytics.view", "analytics.experiments"],
      },
      {
        id: "recommendation-analytics",
        labelKey: "nav.recommendation_analytics",
        labelAr: "إحصائيات التوصيات",
        path: "/dashboard/analytics/recommendations",
        icon: Lightbulb,
        roles: ["admin", "analyst"],
        permissions: ["analytics.view"],
      },
      {
        id: "sentiment-analytics",
        labelKey: "nav.sentiment_analytics",
        labelAr: "تحليل المشاعر",
        path: "/dashboard/sentiment-analytics",
        icon: Brain,
        roles: ["admin", "analyst"],
        permissions: ["analytics.view", "analytics.sentiment"],
      },
      {
        id: "personalization-analytics",
        labelKey: "nav.personalization_analytics",
        labelAr: "تحليلات التخصيص",
        path: "/dashboard/personalization-analytics",
        icon: Target,
        roles: ["admin"],
        permissions: ["analytics.view"],
      },
      {
        id: "article-analytics",
        labelKey: "nav.article_analytics",
        labelAr: "تحليلات المقالات",
        path: "/dashboard/article-analytics",
        icon: BarChart,
        roles: ["admin", "editor", "analyst"],
        permissions: ["analytics.view"],
      },
    ],
  },

  // ===== المحتوى الذكي / Smart Content =====
  {
    id: "smart_content",
    labelKey: "nav.smart_content",
    labelAr: "المحتوى الذكي",
    icon: Grid3x3,
    roles: ["admin"],
    children: [
      {
        id: "smart_blocks",
        labelKey: "nav.smart_blocks",
        labelAr: "البلوكات الذكية",
        path: "/dashboard/smart-blocks",
        icon: Grid3x3,
        roles: ["admin"],
        permissions: ["blocks.view", "blocks.manage"],
      },
      {
        id: "quad_categories_block",
        labelKey: "nav.quad_categories_block",
        labelAr: "بلوك التصنيفات الرباعية",
        path: "/dashboard/blocks/quad-categories",
        icon: SquareStack,
        roles: ["admin"],
        permissions: ["blocks.view", "blocks.manage"],
      },
    ],
  },

  // ===== الإعدادات / Settings =====
  {
    id: "settings",
    labelKey: "nav.settings",
    labelAr: "الإعدادات",
    icon: Settings,
    roles: ["admin"],
    children: [
      {
        id: "rss_feeds",
        labelKey: "nav.rss_feeds",
        labelAr: "مصادر RSS",
        path: "/dashboard/rss-feeds",
        icon: Rss,
        roles: ["admin"],
        permissions: ["settings.view", "rss.manage"],
      },
      {
        id: "integrations",
        labelKey: "nav.integrations",
        labelAr: "التكاملات",
        path: "/dashboard/integrations",
        icon: Plug,
        roles: ["admin"],
        permissions: ["settings.view", "integrations.manage"],
      },
      {
        id: "storage",
        labelKey: "nav.storage",
        labelAr: "التخزين",
        path: "/dashboard/storage",
        icon: Cloud,
        roles: ["admin"],
        permissions: ["settings.view", "storage.manage"],
      },
      {
        id: "audits",
        labelKey: "nav.audit_logs",
        labelAr: "سجلات النشاط",
        path: "/dashboard/audit-logs",
        icon: ListChecks,
        roles: ["admin"],
        permissions: ["system.view_logs"],
      },
      {
        id: "announcements",
        labelKey: "nav.announcements",
        labelAr: "الإعلانات الداخلية",
        path: "/dashboard/announcements",
        icon: Megaphone,
        roles: ["admin"],
        permissions: ["settings.view", "announcements.manage"],
      },
      {
        id: "system_settings",
        labelKey: "nav.system_settings",
        labelAr: "إعدادات النظام",
        path: "/dashboard/system-settings",
        icon: Settings,
        roles: ["admin"],
        permissions: ["system.manage_settings"],
      },
      {
        id: "admin_tools",
        labelKey: "nav.admin_tools",
        labelAr: "أدوات الإدارة",
        path: "/dashboard/admin-tools",
        icon: Wrench,
        roles: ["admin"],
        permissions: ["system.manage_settings"],
      },
      {
        id: "auto_image_settings",
        labelKey: "nav.auto_image_settings",
        labelAr: "التوليد التلقائي للصور",
        path: "/dashboard/auto-image-settings",
        icon: Wand2,
        roles: ["admin"],
        permissions: ["settings.view", "ai.manage"],
      },
      {
        id: "communications",
        labelKey: "nav.communications",
        labelAr: "قنوات الاتصال",
        path: "/dashboard/communications",
        icon: Mail,
        roles: ["admin"],
        permissions: ["settings.view", "communications.manage"],
      },
      {
        id: "editor_alerts",
        labelKey: "nav.editor_alerts",
        labelAr: "تنبيهات رئيس التحرير",
        path: "/dashboard/editor-alerts",
        icon: Bell,
        roles: ["admin"],
        permissions: ["settings.view", "notifications.manage"],
      },
    ],
  },
];
