import Foundation

// نصوص عربية ثابتة لتطبيق خليجي 27 — بدون i18n متعدد اللغات في النسخة الأولى.
enum GcStrings {
    static let strings: [String: String] = [
        "tab.home": "الرئيسية",
        "tab.matches": "المباريات",
        "tab.predictions": "التوقعات",
        "tab.tournament": "البطولة",
        "tab.more": "حسابي",
        "app.title": "خليجي 27",
        "app.host": "السعودية · جدة 2026",
        "brand.by": "من منصة سبق",
        "state.live": "مباشر",
        "state.finished": "انتهت",
        "state.upcoming": "قادمة",
        "state.void": "أُلغيت المباراة — لا تُحتسب",
        "state.void.short": "ملغاة",
        "time.today": "اليوم",
        "time.tomorrow": "غدًا",

        // الرئيسية
        "home.countdown.title": "العدّ التنازلي للانطلاق",
        "home.today.title": "مباريات اليوم",
        "home.next.title": "أقرب المباريات",
        "home.next.empty.title": "لا مباريات قادمة",
        "home.next.empty.subtitle": "ستُحدَّث عند اقتراب الجولة",
        "home.live.title": "مباشر الآن",
        "home.standings.title": "ترتيب المجموعات",
        "home.scorers.title": "الهدّافون",
        "home.history.title": "سجلّ البطولة",
        "home.history.subtitle": "من 1970 إلى اليوم — 26 نسخة",
        "home.holder": "حامل اللقب",
        "home.mostTitles": "الأكثر تتويجًا",
        "home.venues.title": "ملاعب جدة",
        "hero.badge.special": "كأس الخليج العربي",
        "hero.hostedBy": "جدة — السعودية",
        "hero.liveNow": "البطولة منطلقة الآن",
        "hero.coverage": "تغطية خاصة",
        "hero.tagline": "كأس الخليج العربي السابع والعشرون — تغطية حية بتوقيت الرياض",
        "cta.schedule": "المباريات",
        "cta.predict": "توقّع",
        "cta.teams": "البطولة",
        "countdown.days": "يوم",
        "countdown.hours": "ساعة",
        "countdown.minutes": "دقيقة",
        "countdown.seconds": "ثانية",
        "countdown.title": "العدّ التنازلي لانطلاق البطولة",
        "saudi.title": "الأخضر في خليجي 27",
        "saudi.host": "المستضيف",
        "teams.host.badge": "مضيف",

        // المباريات
        "matches.subtitle": "الجدول الكامل بتوقيت الرياض",
        "matchesHero.matches": "مباراة",
        "matchesHero.finished": "منتهية",
        "metric.team": "منتخب",
        "schedule.title": "جدول المباريات",
        "schedule.empty.title": "لا مباريات",
        "schedule.empty.subtitle": "سيُحدَّث الجدول قريبًا",
        "schedule.round.all": "الكل",
        "schedule.day.all": "كل الأيام",

        // البطولة
        "tournament.subtitle": "المجموعات والأدوار والهدّافون والسجلّ",
        "tournament.seg.groups": "المجموعات",
        "tournament.seg.bracket": "الأدوار",
        "tournament.seg.scorers": "الهدّافون",
        "tournament.seg.history": "السجلّ",
        "standings.section.title": "ترتيب المجموعات",
        "standings.section.subtitle": "يتأهل الأول والثاني من كل مجموعة",
        "standings.qualifyLine": "تأهّل 1–2",
        "standings.col.team": "الفريق",
        "standings.col.played": "لعب",
        "standings.col.diff": "+/-",
        "standings.col.points": "نقاط",
        "groups.empty.title": "ستُعلن المجموعات",
        "groups.empty.subtitle": "عقب انطلاق البطولة ستُحدَّث الجداول تلقائيًّا",
        "bracket.title": "الأدوار الإقصائية",
        "bracket.subtitle": "نصف النهائي والنهائي",
        "bracket.semis": "نصف النهائي",
        "bracket.final": "النهائي",
        "bracket.empty.title": "لم تُحدَّد المواجهات بعد",
        "bracket.empty.subtitle": "ستظهر بعد انتهاء دور المجموعات",
        "scorers.title": "هدّافو البطولة",
        "scorers.assists.title": "صنّاع الأهداف",
        "scorers.lastEdition": "أرقام خليجي 26 — بانتظار انطلاق البطولة",
        "scorers.empty.title": "لا أرقام بعد",
        "scorers.empty.subtitle": "تظهر لوحة الهدّافين مع أول أهداف البطولة",
        "scorers.goals": "هدف",
        "scorers.assists": "صناعة",
        "scorers.matches": "مباراة",
        "history.titles.title": "جدول الألقاب",
        "history.editions.title": "كل النسخ",
        "history.titles.unit": "لقب",
        "history.runnerUp.unit": "وصافة",
        "history.hosted.unit": "استضافة",
        "history.champion": "البطل",
        "history.runnerUp": "الوصيف",
        "history.host": "المضيف",
        "history.upcoming": "النسخة القادمة",

        // التوقعات
        "predictions.subtitle": "توقّع وشارك في البركة",
        "predictions.seg.matches": "المباريات",
        "predictions.seg.leaders": "المتصدرون",
        "predictions.seg.long": "البطل والهدّاف",
        "predictions.seg.mine": "سجلّي",
        "predictions.hero.title": "مسابقة التوقعات",
        "predictions.hero.subtitle": "1000 نقطة لكل مباراة تُقسَّم 50/30/20 على النتيجة الدقيقة والفارق والاتجاه",
        "predictions.stat.points": "نقاطي",
        "predictions.stat.exact": "دقيقة",
        "predictions.stat.streak": "سلسلة",
        "predictions.stat.played": "شاركت",
        "predictions.jackpot": "الجائزة المتراكمة",
        "predictions.empty.title": "لا مباريات مفتوحة الآن",
        "predictions.empty.subtitle": "ستظهر مباريات التوقعات عند اقتراب الجولة",
        "predictions.locked": "مغلق",
        "predictions.locked.note": "انتهى وقت التوقّع",
        "predictions.unavailable": "مسابقة التوقعات غير مفعّلة حاليًا",
        "predictions.meta.pool": "البركة",
        "predictions.meta.participant": "مشارك",
        "predictions.meta.prediction": "توقّع",
        "predictions.probs.title": "توقّع النموذج",
        "predictions.crowd.title": "توقّعات الجمهور",
        "predictions.draw": "تعادل",
        "predictions.submit.new": "إرسال التوقّع",
        "predictions.submit.update": "تحديث التوقّع",
        "predictions.submit.saved": "تم الحفظ",
        "predictions.signin.note": "سجّل الدخول بحساب Apple لحفظ توقّعاتك والمنافسة على البركة",
        "predictions.tier.exact": "🎯 النتيجة الدقيقة",
        "predictions.tier.margin": "📏 الفارق الصحيح",
        "predictions.tier.outcome": "✅ الاتجاه الصحيح",
        "predictions.tier.none": "لم تُصِب هذه المرّة",
        "leaderboard.empty.title": "لم يبدأ الترتيب بعد",
        "leaderboard.empty.subtitle": "سيظهر المتصدرون بعد أول جولة توقعات",
        "leaderboard.points": "نقطة",
        "leaderboard.accuracy": "دقّة",
        "long.champion.title": "توقّع بطل خليجي 27",
        "long.champion.subtitle": "بركة 5000 نقطة تُقسَّم على من أصابوا البطل",
        "long.scorer.title": "توقّع هدّاف البطولة",
        "long.scorer.subtitle": "بركة 5000 نقطة — اكتب اسم اللاعب",
        "long.mine": "توقّعك",
        "long.votes": "أكثر الاختيارات",
        "long.locked": "أُغلق باب التوقّع مع انطلاق البطولة",
        "long.scorer.placeholder": "اسم الهدّاف المتوقّع",
        "long.scorer.save": "حفظ توقّع الهدّاف",
        "mine.empty.title": "لا توقّعات بعد",
        "mine.empty.subtitle": "ابدأ بتوقّع أول مباراة مفتوحة",
        "mine.pending": "بانتظار النتيجة",

        // مجالس التوقعات
        "predictions.seg.fantasy": "الفانتازي",
        "majlis.title": "المجالس",
        "majlis.hero.subtitle": "حوّل التوقعات إلى مسامرة يومية مع ناسك طوال البطولة",
        "majlis.hero.private": "خاص بناسك",
        "majlis.hero.reveal": "تُكشف بعد الإقفال",
        "majlis.hero.limit": "حتى 50 عضوًا",
        "majlis.signin.title": "مجلسك ينتظرك",
        "majlis.signin.body": "سجّل الدخول بعضوية سبق لتنشئ مجلسًا أو تنضم إلى دعوة وصلتك.",
        "majlis.create.title": "أنشئ مجلسك",
        "majlis.create.short": "ابدأ المنافسة",
        "majlis.create.body": "اختر اسمًا يعرفه أهلك أو زملاؤك؛ ستحصل فورًا على رمز ورابط دعوة.",
        "majlis.create.field": "اسم المجلس",
        "majlis.create.placeholder": "مثل: ديوانية الجمعة",
        "majlis.create.action": "إنشاء المجلس",
        "majlis.join.title": "انضم إلى مجلس",
        "majlis.join.short": "أدخل رمز الدعوة",
        "majlis.join.body": "أدخل الرمز الذي شاركه معك صاحب المجلس؛ الأحرف الإنجليزية غير حساسة لحالتها.",
        "majlis.join.field": "رمز الدعوة",
        "majlis.join.placeholder": "7KQ2MD",
        "majlis.join.action": "الانضمام",
        "majlis.loading": "يتم تحميل مجالسك",
        "majlis.empty.title": "لا مجالس بعد",
        "majlis.empty.body": "أنشئ مجلسك الأول أو انضم إلى رمز وصلك من صديق.",
        "majlis.mine.title": "مجالسي",
        "majlis.members.count": "{n} عضو",
        "majlis.owner": "صاحب المجلس",
        "majlis.me": "أنا",
        "majlis.moreActions": "المزيد من إجراءات المجلس",
        "majlis.cancel": "إلغاء",
        "majlis.notice.created": "أُنشئ مجلس «{name}» بنجاح",
        "majlis.notice.joined": "انضممت إلى «{name}» 🎉",
        "majlis.notice.deleted": "حُذف المجلس",
        "majlis.notice.left": "غادرت المجلس",

        // دعوة المجلس
        "majlis.invite.title": "دعوة المجلس",
        "majlis.invite.eyebrow": "مجالس توقعات خليجي 27",
        "majlis.invite.joinUs": "انضم إلى مجلس",
        "majlis.invite.tagline": "توقّع قبل المباريات ونافس ناسك",
        "majlis.invite.code": "رمز الدعوة",
        "majlis.invite.share": "ادعُ مجلسك",
        "majlis.invite.preparing": "يتم تجهيز بطاقة الدعوة",
        "majlis.invite.copyLink": "نسخ رابط الدعوة",
        "majlis.invite.copied": "نُسخ رابط الدعوة",
        "majlis.invite.subject": "دعوة إلى مجلس {name}",
        "majlis.invite.shareMessage": "نافسنا في مجلس «{name}» لتوقعات خليجي 27 — رمز الدعوة {code}",
        "majlis.invite.previewA11y": "بطاقة دعوة مجلس {name}، الرمز {code}",
        "majlis.invite.received": "وصلتك دعوة إلى مجلس",
        "majlis.invite.members": "{n} من {max} عضو",
        "majlis.invite.signinFirst": "الدعوة محفوظة. سجّل الدخول أولًا ثم وافق على الانضمام مرة واحدة.",
        "majlis.invite.consent": "بانضمامك سيظهر اسمك وترتيبك وتوقعاتك لأعضاء المجلس بعد إقفال كل مباراة.",
        "majlis.invite.confirm": "أوافق — انضم الآن",
        "majlis.invite.full": "اكتمل العدد؛ إن كنت عضوًا فسيُفتح مجلسك مباشرة",
        "majlis.invite.loading": "يتم التحقق من الدعوة",

        // إعدادات إشعارات المجلس
        "majlis.notifications.title": "إشعارات المجلس",
        "majlis.notifications.body": "قبل الإقفال، وبعد التسوية، وعند انضمام عضو فقط",
        "majlis.notifications.a11y": "يتطلب التفعيل موافقتك على إشعارات النظام",
        "majlis.notifications.enabled": "فُعّلت إشعارات المجلس",
        "majlis.notifications.disabled": "أُوقفت إشعارات المجلس",
        "majlis.notifications.denied": "الإشعارات غير مسموحة من إعدادات الجهاز",

        // تعريف المجلس
        "majlis.onboarding.rank.title": "هنا ترتيبك بين ناسك",
        "majlis.onboarding.rank.body": "بدل أن تنافس آلاف الغرباء، سترى مركزك مباشرة بين أهلك وأصدقائك.",
        "majlis.onboarding.reveal.title": "توقّعاتهم تبقى سرًا",
        "majlis.onboarding.reveal.body": "قبل الإقفال يظهر فقط من توقّع. وبعد صافرة البداية تنكشف النتائج ويبدأ النقاش.",
        "majlis.onboarding.invite.title": "كبّر ديوانيتك",
        "majlis.onboarding.invite.body": "ادعُ حتى 50 عضوًا ببطاقة جاهزة ورابط يفتح المجلس مباشرة.",
        "majlis.onboarding.skip": "تخطّي",
        "majlis.onboarding.next": "التالي",
        "majlis.onboarding.predictNow": "توقّع مباراة اليوم الآن",
        "majlis.onboarding.progress": "الصفحة {current} من {total}",
        "majlis.onboarding.alerts.title": "نبّهني بلحظات المجلس المهمة",
        "majlis.onboarding.alerts.body": "ثلاثة أنواع فقط، ويمكن إيقافها في أي وقت.",

        // تفاصيل المجلس والجولة
        "majlis.detail.matchday": "الجولة",
        "majlis.detail.ranking": "الترتيب",
        "majlis.detail.fantasy": "الفانتازي",
        "majlis.detail.champion": "البطل",
        "majlis.detail.duels": "التحديات",
        "majlis.detail.harvest": "الحصاد",
        "majlis.detail.revealPromise": "النتائج لا تنكشف قبل الإقفال",
        "majlis.matchday.title": "يوم المباريات",
        "majlis.matchday.previous": "اليوم السابق",
        "majlis.matchday.next": "اليوم التالي",
        "majlis.matchday.loading": "يتم تحميل توقعات المجلس",
        "majlis.matchday.empty.title": "لا مباريات في هذا اليوم",
        "majlis.matchday.empty.body": "انتقل إلى يوم آخر أو عُد عند اقتراب الجولة.",
        "majlis.match.sealed": "التوقعات مختومة",
        "majlis.match.revealed": "انكشفت التوقعات",
        "majlis.match.predicted": "توقّع ✓",
        "majlis.match.notYet": "لم يتوقّع",
        "majlis.match.noPrediction": "لم يشارك في هذه المباراة",
        "majlis.match.focused": "هذه المباراة المرتبطة بالإشعار",
        "majlis.champion.today": "بطل اليوم",
        "majlis.champion.tie": "أبطال اليوم",
        "majlis.champion.inProgress": "تُسوّى الجولة الآن: {settled} من {total} مباريات",

        // ترتيب وفانتازي وبطل المجلس
        "majlis.ranking.leader": "متصدر المجلس",
        "majlis.ranking.stats": "{correct} إصابة · {exact} دقيقة",
        "majlis.ranking.loading": "يتم تحميل ترتيب المجلس",
        "majlis.ranking.empty.title": "الترتيب لم يبدأ",
        "majlis.ranking.empty.body": "تظهر المراكز بعد أول مباراة مسوّاة.",
        "majlis.fantasy.title": "فانتازي المجلس",
        "majlis.fantasy.body": "ترتيب تشكيلات أعضاء المجلس فقط",
        "majlis.fantasy.noSquad": "لم يكوّن تشكيلة بعد",
        "majlis.fantasy.loading": "يتم تحميل فانتازي المجلس",
        "majlis.fantasy.empty.title": "لا تشكيلات بعد",
        "majlis.fantasy.empty.body": "كوّن تشكيلتك من تبويب الفانتازي وابدأ المنافسة.",
        "majlis.championPicks.sealed": "الاختيارات مختومة حتى إقفال توقع البطل",
        "majlis.championPicks.revealed": "اختيارات أعضاء المجلس للبطل",
        "majlis.championPicks.picked": "اختار ✓",
        "majlis.championPicks.notPicked": "لم يختر",
        "majlis.championPicks.noPick": "بلا اختيار",
        "majlis.championPicks.loading": "يتم تحميل اختيارات البطل",
        "majlis.championPicks.empty.title": "لا اختيارات بعد",
        "majlis.championPicks.empty.body": "ستظهر مشاركة الأعضاء هنا.",

        // التحديات
        "majlis.duels.title": "تحديات 1×1",
        "majlis.duels.body": "تحدَّ عضوًا على مباراة بنقاط الولاء",
        "majlis.duels.create": "تحدٍ جديد",
        "majlis.duels.loading": "يتم تحميل التحديات",
        "majlis.duels.empty.title": "لا تحديات بعد",
        "majlis.duels.empty.body": "اختر عضوًا ومباراة وابدأ أول تحدٍ.",
        "majlis.duels.vs": "ضد",
        "majlis.duels.accept": "قبول",
        "majlis.duels.decline": "رفض",
        "majlis.duels.cancel": "إلغاء التحدي",
        "majlis.duels.opponent": "العضو المنافس",
        "majlis.duels.chooseOpponent": "اختر عضوًا",
        "majlis.duels.match": "المباراة",
        "majlis.duels.chooseMatch": "اختر مباراة",
        "majlis.duels.stake": "نقاط التحدي",
        "majlis.duels.send": "إرسال التحدي",
        "majlis.duels.status.pending": "بانتظار الرد",
        "majlis.duels.status.accepted": "مقبول",
        "majlis.duels.status.declined": "مرفوض",
        "majlis.duels.status.cancelled": "ملغى",
        "majlis.duels.status.expired": "انتهت صلاحيته",
        "majlis.duels.status.settled": "تمت التسوية",

        // حصاد البطولة
        "majlis.harvest.title": "حصاد المجلس",
        "majlis.harvest.champion": "بطل المجلس",
        "majlis.harvest.accurate": "الأدق",
        "majlis.harvest.accurate.detail": "دقة {accuracy}",
        "majlis.harvest.bold": "الأجرأ",
        "majlis.harvest.bold.detail": "أصاب اختيارًا باحتمال {prob}",
        "majlis.harvest.stubborn": "العنيد",
        "majlis.harvest.stubborn.detail": "اختار {team} في {n} مباريات",
        "majlis.harvest.loading": "يتم تجهيز حصاد المجلس",
        "majlis.harvest.pending.title": "الحصاد بعد النهائي",
        "majlis.harvest.pending.body": "تُفتح بطاقة أبطال المجلس وألقابه فور نهاية البطولة.",
        "majlis.harvest.share": "شارك حصاد المجلس",
        "majlis.harvest.shareMessage": "هذا حصاد مجلس «{name}» في توقعات خليجي 27 🏆",
        "majlis.harvest.shareCard.subtitle": "14 يومًا من التوقعات والمنافسة",

        // مغادرة وحذف
        "majlis.leave.action": "مغادرة المجلس",
        "majlis.leave.confirm.title": "مغادرة هذا المجلس؟",
        "majlis.leave.confirm.body": "ستختفي من ترتيب المجلس ويمكنك العودة لاحقًا برمز الدعوة.",
        "majlis.leave.confirm.action": "نعم، غادر",
        "majlis.delete.action": "حذف المجلس",
        "majlis.delete.confirm.title": "حذف المجلس نهائيًا؟",
        "majlis.delete.confirm.body": "سيُزال المجلس من جميع أعضائه ولا يمكن التراجع عن ذلك.",
        "majlis.delete.confirm.action": "حذف نهائي",

        // مركز المباراة
        "match.title": "مركز المباراة",
        "match.seg.summary": "ملخّص",
        "match.seg.lineups": "التشكيلات",
        "match.seg.stats": "إحصاءات",
        "match.seg.h2h": "مواجهات",
        "match.events": "أحداث المباراة",
        "match.noEvents.title": "لا أحداث بعد",
        "match.noEvents.subtitle": "يبدأ شريط الأحداث مع صافرة البداية",
        "match.lineups.empty.title": "لم تُعلن التشكيلات",
        "match.lineups.empty.subtitle": "تظهر قبل انطلاق المباراة بنحو ساعة",
        "match.stats.empty.title": "لا إحصاءات بعد",
        "match.stats.empty.subtitle": "تظهر الأرقام مع انطلاق المباراة",
        "match.h2h.record": "الرصيد التاريخي",
        "match.h2h.recent": "آخر المواجهات",
        "match.h2h.tournament": "مواجهات في البطولة",
        "match.h2h.empty.title": "لا سجلّ مواجهات",
        "match.h2h.empty.subtitle": "أول مواجهة بين المنتخبين منذ سنوات",
        "match.wins": "فوز",
        "match.draws": "تعادل",
        "match.coach": "المدرّب",
        "match.formation": "الخطّة",
        "match.startXI": "التشكيلة الأساسية",
        "match.subs": "البدلاء",
        "match.info.venue": "الملعب",
        "match.info.date": "التاريخ",
        "match.info.time": "الوقت",
        "match.info.matchNo": "رقم المباراة",
        "match.loading": "يتم تحميل تفاصيل المباراة",
        "liveActivity.start": "متابعة على شاشة القفل",
        "liveActivity.stop": "إيقاف المتابعة",

        // المنتخب
        "team.subtitle.group": "في {group}",
        "team.nextMatch": "المباراة القادمة",
        "team.fixtures": "جدول المنتخب",
        "team.group": "مجموعته",
        "team.squad": "قائمة المنتخب",
        "team.form": "آخر النتائج",
        "team.legacy.title": "الإرث الخليجي",
        "team.legacy.years": "سنوات التتويج",
        "team.coach": "المدرّب",
        "team.squad.empty.title": "لم تُعلن القائمة",
        "team.squad.empty.subtitle": "تظهر قائمة اللاعبين فور اعتمادها",
        "position.Goalkeeper": "حراسة المرمى",
        "position.Defender": "الدفاع",
        "position.Midfielder": "الوسط",
        "position.Attacker": "الهجوم",
        "stats.played": "لعب",
        "stats.points": "نقاط",
        "stats.diff": "فارق",
        "stats.win": "فوز",
        "stats.draw": "تعادل",
        "stats.lose": "خسارة",
        "stats.goalsFor": "له",
        "stats.goalsAgainst": "عليه",

        // حسابي / الإعدادات
        "more.subtitle": "حسابك وإعدادات التطبيق",
        "more.guest.title": "أهلاً بك في خليجي 27",
        "more.guest.subtitle": "سجّل دخولك لحفظ توقعاتك، والمشاركة في البركة، ومتابعة نقاطك على كل أجهزتك.",
        "more.benefit.predictions": "حفظ التوقعات والمشاركة في البركة",
        "more.benefit.rank": "الظهور في لوحة المتصدرين",
        "more.benefit.fantasy": "فريق فانتازي ومجلس الأصدقاء",
        "more.section.activity": "نشاطي",
        "more.activity.predictions": "توقعاتي",
        "more.activity.predictions.sub": "المباريات والنقاط",
        "more.section.settings": "الإعدادات",
        "more.settings.liveAlerts": "تنبيهات المباريات المباشرة",
        "more.settings.liveAlerts.sub": "عند انطلاق مباراة أو هدف",
        "more.settings.reminders": "تذكير التوقعات",
        "more.settings.reminders.sub": "قبل صافرة البداية",
        "more.settings.haptics": "اهتزاز اللمس",
        "more.settings.haptics.sub": "تغذية راجعة عند الضغط",
        "more.section.links": "روابط",
        "more.link.web": "صفحة خليجي 27 على سبق",
        "more.link.share": "مشاركة التطبيق",
        "more.link.share.message": "تابع خليجي 27 مع سبق — تغطية وتوقعات حية",
        "more.about.title": "عن البطولة",
        "more.about.body": "النسخة 27 من كأس الخليج العربي — تستضيفها السعودية في جدة من 23 سبتمبر إلى 6 أكتوبر 2026، بمشاركة 8 منتخبات على ملعبَي مدينة الملك عبدالله الرياضية والأمير عبدالله الفيصل.",
        "more.version": "الإصدار",
        "teams.section.title": "منتخبات البطولة",
        "teams.empty.title": "ستظهر المنتخبات",
        "teams.empty.subtitle": "فور تحميل بيانات البطولة",
        "venues.section.title": "ملاعب الاستضافة",
        "venues.guide.title": "دليل الحضور — جدة",
        "tournament.seg.guide": "الدليل",
        "account.title": "حسابي",
        "account.subtitle": "لحفظ التوقعات والمشاركة في البركة",
        "account.signout": "تسجيل الخروج",
        "account.member.fallback": "عضو سبق",
        "account.signedIn": "مسجّل الدخول",
        "account.signin.note": "سجّل الدخول بعضوية سبق لحفظ توقّعاتك في مسابقة خليجي 27",
        "account.guest": "زائر",

        // حسابي — الهوية والإحصائيات
        "account.verified.apple": "موثّق بحساب Apple",
        "account.verified.member": "عضوية سبق",

        // مصادقة عضوية سبق
        "auth.welcome.prefix": "مرحبًا بك في",
        "auth.welcome.product": "أحد منتجات",
        "auth.welcome.sabq": "صحيفة سبق",
        "auth.welcome.note": "سجّل دخولك لحفظ توقعاتك، والمشاركة في البركة، ومتابعة نقاطك على كل أجهزتك.",
        "auth.sabq.badge": "عضوية سبق",
        "auth.tab.phone": "الجوال",
        "auth.tab.membership": "عضوية سبق",
        "auth.field.identifier": "البريد الإلكتروني أو الجوال",
        "auth.field.password": "كلمة المرور",
        "auth.cta.membership": "الدخول بعضوية سبق",
        "auth.cta.signin": "تسجيل الدخول",
        "auth.or": "أو",
        "auth.close": "إغلاق",
        "auth.phone.hint": "سنرسل رمز تحقّق برسالة نصية إلى جوالك.",
        "auth.phone.send": "أرسل رمز التحقق",
        "auth.phone.enterCode": "أدخل رمز التحقق",
        "auth.phone.sentTo": "أُرسل إلى",
        "auth.phone.edit": "تعديل",
        "auth.phone.resend": "إعادة إرسال الرمز",
        "auth.phone.resendIn": "إعادة الإرسال خلال {n} ثانية",
        "auth.phone.verify": "تحقّق ودخول",
        "auth.phone.sent": "تم إرسال رمز التحقق",
        "auth.phone.sendFailed": "تعذّر إرسال رمز التحقق",
        "auth.error.emptyCredentials": "أدخل البريد/الجوال وكلمة المرور",
        "auth.error.unauthorized": "بيانات الدخول غير صحيحة",
        "auth.error.rateLimited": "محاولات كثيرة، حاول بعد قليل",
        "auth.error.generic": "تعذّر تسجيل الدخول",
        // المصادقة الثنائية
        "auth.2fa.title": "التحقّق بخطوتين",
        "auth.2fa.subtitle.totp": "أدخل الرمز المكوّن من ٦ أرقام من تطبيق المصادقة",
        "auth.2fa.subtitle.backup": "أدخل أحد الرموز الاحتياطية",
        "auth.2fa.backupPlaceholder": "الرمز الاحتياطي",
        "auth.2fa.verify": "تحقّق",
        "auth.2fa.useBackup": "استخدام رمز احتياطي",
        "auth.2fa.useApp": "استخدام رمز التطبيق",
        "auth.2fa.back": "رجوع",
        "auth.2fa.invalidCode": "رمز التحقق غير صحيح",
        "account.stat.points": "نقطة بركة",
        "account.stat.rank": "ترتيبي العام",
        "account.stat.accuracy": "دقة توقعاتي",
        "account.teaser.jackpot": "بركة اليوم",
        "account.teaser.players": "متوقّع منافس",
        "account.streak.text": "سلسلة مشتعلة: {n} توقعات صائبة متتالية",
        "account.streak.share": "سلسلتي في توقعات خليجي 27 وصلت {n} إصابات متتالية 🔥 نافسني في تطبيق خليجي من سبق",
        "account.badges.title": "أوسمتي",
        "account.badges.subtitle": "إنجازات دائمة صنعتها في التوقعات والمجالس",
        "account.badges.unlocked": "مفتوح",
        "account.badge.majlisChampion": "بطل المجلس",
        "account.badge.majlisChampion.desc": "أنهيت البطولة في صدارة أحد مجالسك",
        "account.badge.majlisDean": "عميد المجلس",
        "account.badge.majlisDean.desc": "أوصلت أحد مجالسك إلى 10 أعضاء",
        "account.badge.nostradamus": "نوسترداموس",
        "account.badge.nostradamus.desc": "أصبت النتيجة الدقيقة في 5 مباريات",
        "account.badge.lionheart": "قلب الأسد",
        "account.badge.lionheart.desc": "أصبت نتيجة لم يتوقعها إلا القليل",
        "account.badge.hotStreak": "سلسلة ملتهبة",
        "account.badge.hotStreak.desc": "حققت 3 إصابات متتالية أو أكثر",
        "account.badge.everPresent": "الحاضر دومًا",
        "account.badge.everPresent.desc": "شاركت في كل مباريات دور المجموعات",
        "account.badge.earned": "وسام مستحق",
        "account.pts": "نقطة",
        "account.fantasy.title": "فريقي الفانتازي",
        "account.fantasy.empty": "كوّن فريقك",
        "account.fantasy.cta": "8 لاعبين وميزانية 100",
        "account.fantasy.rank": "المركز {n} بين المنافسين",
        "account.fantasy.manage": "إدارة التشكيلة",
        "account.majlis.title": "مجالسي",
        "account.majlis.empty": "أنشئ مجلسًا",
        "account.majlis.count": "{n} مجالس",
        "account.majlis.owner": "أنت صاحب «{name}»",
        "account.majlis.cta": "نافس أصدقاءك بكود خاص",
        "account.log.title": "سجل توقعاتي",
        "account.log.empty": "لم تتوقع بعد — ابدأ من تبويب التوقعات",
        "account.log.all": "عرض السجل كاملًا",
        "account.log.myPick": "توقعي: {score}",
        "account.log.miss": "لم يتحقق",
        "account.log.pending": "بالانتظار",
        "account.log.champion": "توقعي للبطل",
        "account.log.topScorer": "هدّاف البطولة",
        "account.fav.title": "منتخبي المفضل",
        "account.fav.set": "منتخبي: {team}",
        "account.fav.subtitle": "مبارياته تتصدر جدول المباريات",
        "account.fav.choose": "اختيار",
        "account.fav.change": "تغيير",
        "account.fav.none": "بدون تفضيل",
        "account.tools.title": "أدوات",
        "account.tools.widget": "ويدجت الشاشة الرئيسية",
        "account.tools.widget.sub": "مباراة اليوم وترتيب المجموعة على شاشتك",
        "account.tools.card": "بطاقة إنجازي",
        "account.tools.card.sub": "صورة جاهزة للمشاركة بنقاطي وترتيبي",
        "account.card.tagline": "متوقّع في مسابقة خليجي 27",
        "account.card.streak": "سلسلة",
        "account.card.footer": "توقّع ونافس — تطبيق خليجي 27 من سبق",
        "account.widget.title": "أضف الويدجت لشاشتك",
        "account.widget.step1": "اضغط مطوّلًا على مساحة فارغة في الشاشة الرئيسية",
        "account.widget.step2": "اختر زر الإضافة (+) أعلى الشاشة ثم ابحث عن «خليجي 27»",
        "account.widget.step3": "اختر الحجم المناسب واضغط «إضافة الويدجت»",
        "account.widget.live": "أثناء المباريات المباشرة ستظهر النتيجة لحظة بلحظة في الأنشطة الحية على شاشة القفل وDynamic Island",
        "account.widget.done": "تم",

        // عام
        "refresh.error.title": "تعذّر التحديث",
        "refresh.retry": "إعادة المحاولة",
        "loading.hub": "يتم تجهيز مركز البطولة",
        "loading.matches": "يتم تحديث جدول المباريات",
        "loading.standings": "يتم تحديث الترتيب",
        "loading.predictions": "يتم تحميل مباريات التوقعات",
        "loading.team": "يتم تحميل بيانات المنتخب",
        "loading.scorers": "يتم تحميل لوحة الهدّافين",
        "loading.history": "يتم تحميل سجلّ البطولة",
    ]

    static func text(_ key: String, _ vars: [String: String] = [:]) -> String {
        var s = strings[key] ?? key
        for (k, v) in vars {
            s = s.replacingOccurrences(of: "{\(k)}", with: v)
        }
        return s
    }
}

func L(_ key: String, _ vars: [String: String] = [:]) -> String {
    GcStrings.text(key, vars)
}

func LTeam(_ id: String, fallback: String) -> String { fallback }

func LRound(_ roundEn: String, fallback: String) -> String { fallback.isEmpty ? roundEn : fallback }

func LError(_ error: Error) -> String {
    if let api = error as? APIError { return api.errorDescription ?? "حدث خطأ" }
    return "تعذّر تحميل البيانات"
}
