import Foundation

// نصوص عربية ثابتة لتطبيق خليجي 27 — بدون i18n متعدد اللغات في النسخة الأولى.
enum GcStrings {
    static let strings: [String: String] = [
        "tab.home": "الرئيسية",
        "tab.matches": "المباريات",
        "tab.predictions": "التوقعات",
        "tab.tournament": "البطولة",
        "tab.more": "حسابي",
        "app.title": "خليجي 27",
        "app.host": "السعودية · جدة 2026",
        "brand.by": "من منصة سبق",
        "state.live": "مباشر",
        "state.finished": "انتهت",
        "state.upcoming": "قادمة",
        "time.today": "اليوم",
        "time.tomorrow": "غدًا",

        // الرئيسية
        "home.countdown.title": "العدّ التنازلي للانطلاق",
        "home.today.title": "مباريات اليوم",
        "home.next.title": "أقرب المباريات",
        "home.next.empty.title": "لا مباريات قادمة",
        "home.next.empty.subtitle": "ستُحدَّث عند اقتراب الجولة",
        "home.live.title": "مباشر الآن",
        "home.standings.title": "ترتيب المجموعات",
        "home.scorers.title": "الهدّافون",
        "home.history.title": "سجلّ البطولة",
        "home.history.subtitle": "من 1970 إلى اليوم — 26 نسخة",
        "home.holder": "حامل اللقب",
        "home.mostTitles": "الأكثر تتويجًا",
        "home.venues.title": "ملاعب جدة",
        "hero.badge.special": "كأس الخليج العربي",
        "hero.hostedBy": "جدة — السعودية",
        "hero.liveNow": "البطولة منطلقة الآن",
        "hero.coverage": "تغطية خاصة",
        "hero.tagline": "كأس الخليج العربي السابع والعشرون — تغطية حية بتوقيت الرياض",
        "cta.schedule": "المباريات",
        "cta.predict": "توقّع",
        "cta.teams": "البطولة",
        "countdown.days": "يوم",
        "countdown.hours": "ساعة",
        "countdown.minutes": "دقيقة",
        "countdown.seconds": "ثانية",
        "countdown.title": "العدّ التنازلي لانطلاق البطولة",
        "saudi.title": "الأخضر في خليجي 27",
        "saudi.host": "المستضيف",
        "teams.host.badge": "مضيف",

        // المباريات
        "matches.subtitle": "الجدول الكامل بتوقيت الرياض",
        "matchesHero.matches": "مباراة",
        "matchesHero.finished": "منتهية",
        "metric.team": "منتخب",
        "schedule.title": "جدول المباريات",
        "schedule.empty.title": "لا مباريات",
        "schedule.empty.subtitle": "سيُحدَّث الجدول قريبًا",
        "schedule.round.all": "الكل",
        "schedule.day.all": "كل الأيام",

        // البطولة
        "tournament.subtitle": "المجموعات والأدوار والهدّافون والسجلّ",
        "tournament.seg.groups": "المجموعات",
        "tournament.seg.bracket": "الأدوار",
        "tournament.seg.scorers": "الهدّافون",
        "tournament.seg.history": "السجلّ",
        "standings.section.title": "ترتيب المجموعات",
        "standings.section.subtitle": "يتأهل الأول والثاني من كل مجموعة",
        "standings.qualifyLine": "تأهّل 1–2",
        "standings.col.team": "الفريق",
        "standings.col.played": "لعب",
        "standings.col.diff": "+/-",
        "standings.col.points": "نقاط",
        "groups.empty.title": "ستُعلن المجموعات",
        "groups.empty.subtitle": "عقب انطلاق البطولة ستُحدَّث الجداول تلقائيًّا",
        "bracket.title": "الأدوار الإقصائية",
        "bracket.subtitle": "نصف النهائي والنهائي",
        "bracket.semis": "نصف النهائي",
        "bracket.final": "النهائي",
        "bracket.empty.title": "لم تُحدَّد المواجهات بعد",
        "bracket.empty.subtitle": "ستظهر بعد انتهاء دور المجموعات",
        "scorers.title": "هدّافو البطولة",
        "scorers.assists.title": "صنّاع الأهداف",
        "scorers.lastEdition": "أرقام خليجي 26 — بانتظار انطلاق البطولة",
        "scorers.empty.title": "لا أرقام بعد",
        "scorers.empty.subtitle": "تظهر لوحة الهدّافين مع أول أهداف البطولة",
        "scorers.goals": "هدف",
        "scorers.assists": "صناعة",
        "scorers.matches": "مباراة",
        "history.titles.title": "جدول الألقاب",
        "history.editions.title": "كل النسخ",
        "history.titles.unit": "لقب",
        "history.runnerUp.unit": "وصافة",
        "history.hosted.unit": "استضافة",
        "history.champion": "البطل",
        "history.runnerUp": "الوصيف",
        "history.host": "المضيف",
        "history.upcoming": "النسخة القادمة",

        // التوقعات
        "predictions.subtitle": "توقّع وشارك في البركة",
        "predictions.seg.matches": "المباريات",
        "predictions.seg.leaders": "المتصدرون",
        "predictions.seg.long": "البطل والهدّاف",
        "predictions.seg.mine": "سجلّي",
        "predictions.hero.title": "مسابقة التوقعات",
        "predictions.hero.subtitle": "1000 نقطة لكل مباراة تُقسَّم 50/30/20 على النتيجة الدقيقة والفارق والاتجاه",
        "predictions.stat.points": "نقاطي",
        "predictions.stat.exact": "دقيقة",
        "predictions.stat.streak": "سلسلة",
        "predictions.stat.played": "شاركت",
        "predictions.jackpot": "الجائزة المتراكمة",
        "predictions.empty.title": "لا مباريات مفتوحة الآن",
        "predictions.empty.subtitle": "ستظهر مباريات التوقعات عند اقتراب الجولة",
        "predictions.locked": "مغلق",
        "predictions.locked.note": "انتهى وقت التوقّع",
        "predictions.unavailable": "مسابقة التوقعات غير مفعّلة حاليًا",
        "predictions.meta.pool": "البركة",
        "predictions.meta.participant": "مشارك",
        "predictions.meta.prediction": "توقّع",
        "predictions.probs.title": "توقّع النموذج",
        "predictions.crowd.title": "توقّعات الجمهور",
        "predictions.draw": "تعادل",
        "predictions.submit.new": "إرسال التوقّع",
        "predictions.submit.update": "تحديث التوقّع",
        "predictions.submit.saved": "تم الحفظ",
        "predictions.signin.note": "سجّل الدخول بحساب Apple لحفظ توقّعاتك والمنافسة على البركة",
        "predictions.tier.exact": "🎯 النتيجة الدقيقة",
        "predictions.tier.margin": "📏 الفارق الصحيح",
        "predictions.tier.outcome": "✅ الاتجاه الصحيح",
        "predictions.tier.none": "لم تُصِب هذه المرّة",
        "leaderboard.empty.title": "لم يبدأ الترتيب بعد",
        "leaderboard.empty.subtitle": "سيظهر المتصدرون بعد أول جولة توقعات",
        "leaderboard.points": "نقطة",
        "leaderboard.accuracy": "دقّة",
        "long.champion.title": "توقّع بطل خليجي 27",
        "long.champion.subtitle": "بركة 5000 نقطة تُقسَّم على من أصابوا البطل",
        "long.scorer.title": "توقّع هدّاف البطولة",
        "long.scorer.subtitle": "بركة 5000 نقطة — اكتب اسم اللاعب",
        "long.mine": "توقّعك",
        "long.votes": "أكثر الاختيارات",
        "long.locked": "أُغلق باب التوقّع مع انطلاق البطولة",
        "long.scorer.placeholder": "اسم الهدّاف المتوقّع",
        "long.scorer.save": "حفظ توقّع الهدّاف",
        "mine.empty.title": "لا توقّعات بعد",
        "mine.empty.subtitle": "ابدأ بتوقّع أول مباراة مفتوحة",
        "mine.pending": "بانتظار النتيجة",

        // مركز المباراة
        "match.title": "مركز المباراة",
        "match.seg.summary": "ملخّص",
        "match.seg.lineups": "التشكيلات",
        "match.seg.stats": "إحصاءات",
        "match.seg.h2h": "مواجهات",
        "match.events": "أحداث المباراة",
        "match.noEvents.title": "لا أحداث بعد",
        "match.noEvents.subtitle": "يبدأ شريط الأحداث مع صافرة البداية",
        "match.lineups.empty.title": "لم تُعلن التشكيلات",
        "match.lineups.empty.subtitle": "تظهر قبل انطلاق المباراة بنحو ساعة",
        "match.stats.empty.title": "لا إحصاءات بعد",
        "match.stats.empty.subtitle": "تظهر الأرقام مع انطلاق المباراة",
        "match.h2h.record": "الرصيد التاريخي",
        "match.h2h.recent": "آخر المواجهات",
        "match.h2h.tournament": "مواجهات في البطولة",
        "match.h2h.empty.title": "لا سجلّ مواجهات",
        "match.h2h.empty.subtitle": "أول مواجهة بين المنتخبين منذ سنوات",
        "match.wins": "فوز",
        "match.draws": "تعادل",
        "match.coach": "المدرّب",
        "match.formation": "الخطّة",
        "match.startXI": "التشكيلة الأساسية",
        "match.subs": "البدلاء",
        "match.info.venue": "الملعب",
        "match.info.date": "التاريخ",
        "match.info.time": "الوقت",
        "match.info.matchNo": "رقم المباراة",
        "match.loading": "يتم تحميل تفاصيل المباراة",
        "liveActivity.start": "متابعة على شاشة القفل",
        "liveActivity.stop": "إيقاف المتابعة",

        // المنتخب
        "team.subtitle.group": "في {group}",
        "team.nextMatch": "المباراة القادمة",
        "team.fixtures": "جدول المنتخب",
        "team.group": "مجموعته",
        "team.squad": "قائمة المنتخب",
        "team.form": "آخر النتائج",
        "team.legacy.title": "الإرث الخليجي",
        "team.legacy.years": "سنوات التتويج",
        "team.coach": "المدرّب",
        "team.squad.empty.title": "لم تُعلن القائمة",
        "team.squad.empty.subtitle": "تظهر قائمة اللاعبين فور اعتمادها",
        "position.Goalkeeper": "حراسة المرمى",
        "position.Defender": "الدفاع",
        "position.Midfielder": "الوسط",
        "position.Attacker": "الهجوم",
        "stats.played": "لعب",
        "stats.points": "نقاط",
        "stats.diff": "فارق",
        "stats.win": "فوز",
        "stats.draw": "تعادل",
        "stats.lose": "خسارة",
        "stats.goalsFor": "له",
        "stats.goalsAgainst": "عليه",

        // حسابي / الإعدادات
        "more.subtitle": "حسابك وإعدادات التطبيق",
        "more.guest.title": "أهلاً بك في خليجي 27",
        "more.guest.subtitle": "سجّل دخولك لحفظ توقعاتك، والمشاركة في البركة، ومتابعة نقاطك على كل أجهزتك.",
        "more.benefit.predictions": "حفظ التوقعات والمشاركة في البركة",
        "more.benefit.rank": "الظهور في لوحة المتصدرين",
        "more.benefit.fantasy": "فريق فانتازي ومجلس الأصدقاء",
        "more.section.activity": "نشاطي",
        "more.activity.predictions": "توقعاتي",
        "more.activity.predictions.sub": "المباريات والنقاط",
        "more.section.settings": "الإعدادات",
        "more.settings.liveAlerts": "تنبيهات المباريات المباشرة",
        "more.settings.liveAlerts.sub": "عند انطلاق مباراة أو هدف",
        "more.settings.reminders": "تذكير التوقعات",
        "more.settings.reminders.sub": "قبل صافرة البداية",
        "more.settings.haptics": "اهتزاز اللمس",
        "more.settings.haptics.sub": "تغذية راجعة عند الضغط",
        "more.section.links": "روابط",
        "more.link.web": "صفحة خليجي 27 على سبق",
        "more.link.share": "مشاركة التطبيق",
        "more.link.share.message": "تابع خليجي 27 مع سبق — تغطية وتوقعات حية",
        "more.about.title": "عن البطولة",
        "more.about.body": "النسخة 27 من كأس الخليج العربي — تستضيفها السعودية في جدة من 23 سبتمبر إلى 6 أكتوبر 2026، بمشاركة 8 منتخبات على ملعبَي مدينة الملك عبدالله الرياضية والأمير عبدالله الفيصل.",
        "more.version": "الإصدار",
        "teams.section.title": "منتخبات البطولة",
        "teams.empty.title": "ستظهر المنتخبات",
        "teams.empty.subtitle": "فور تحميل بيانات البطولة",
        "venues.section.title": "ملاعب الاستضافة",
        "venues.guide.title": "دليل الحضور — جدة",
        "tournament.seg.guide": "الدليل",
        "account.title": "حسابي",
        "account.subtitle": "لحفظ التوقعات والمشاركة في البركة",
        "account.signout": "تسجيل الخروج",
        "account.member.fallback": "عضو سبق",
        "account.signedIn": "مسجّل الدخول",
        "account.signin.note": "سجّل الدخول بعضوية سبق لحفظ توقّعاتك في مسابقة خليجي 27",
        "account.guest": "زائر",

        // حسابي — الهوية والإحصائيات
        "account.verified.apple": "موثّق بحساب Apple",
        "account.verified.member": "عضوية سبق",

        // مصادقة عضوية سبق
        "auth.welcome.prefix": "مرحبًا بك في",
        "auth.welcome.product": "أحد منتجات",
        "auth.welcome.sabq": "صحيفة سبق",
        "auth.welcome.note": "سجّل دخولك لحفظ توقعاتك، والمشاركة في البركة، ومتابعة نقاطك على كل أجهزتك.",
        "auth.sabq.badge": "عضوية سبق",
        "auth.tab.phone": "الجوال",
        "auth.tab.membership": "عضوية سبق",
        "auth.field.identifier": "البريد الإلكتروني أو الجوال",
        "auth.field.password": "كلمة المرور",
        "auth.cta.membership": "الدخول بعضوية سبق",
        "auth.cta.signin": "تسجيل الدخول",
        "auth.or": "أو",
        "auth.close": "إغلاق",
        "auth.phone.hint": "سنرسل رمز تحقّق برسالة نصية إلى جوالك.",
        "auth.phone.send": "أرسل رمز التحقق",
        "auth.phone.enterCode": "أدخل رمز التحقق",
        "auth.phone.sentTo": "أُرسل إلى",
        "auth.phone.edit": "تعديل",
        "auth.phone.resend": "إعادة إرسال الرمز",
        "auth.phone.resendIn": "إعادة الإرسال خلال {n} ثانية",
        "auth.phone.verify": "تحقّق ودخول",
        "auth.phone.sent": "تم إرسال رمز التحقق",
        "auth.phone.sendFailed": "تعذّر إرسال رمز التحقق",
        "auth.error.emptyCredentials": "أدخل البريد/الجوال وكلمة المرور",
        "auth.error.unauthorized": "بيانات الدخول غير صحيحة",
        "auth.error.rateLimited": "محاولات كثيرة، حاول بعد قليل",
        "auth.error.generic": "تعذّر تسجيل الدخول",
        "account.stat.points": "نقطة بركة",
        "account.stat.rank": "ترتيبي العام",
        "account.stat.accuracy": "دقة توقعاتي",
        "account.teaser.jackpot": "بركة اليوم",
        "account.teaser.players": "متوقّع منافس",
        "account.streak.text": "سلسلة مشتعلة: {n} توقعات صائبة متتالية",
        "account.streak.share": "سلسلتي في توقعات خليجي 27 وصلت {n} إصابات متتالية 🔥 نافسني في تطبيق خليجي من سبق",
        "account.pts": "نقطة",
        "account.fantasy.title": "فريقي الفانتازي",
        "account.fantasy.empty": "كوّن فريقك",
        "account.fantasy.cta": "8 لاعبين وميزانية 100",
        "account.fantasy.rank": "المركز {n} بين المنافسين",
        "account.fantasy.manage": "إدارة التشكيلة",
        "account.majlis.title": "مجالسي",
        "account.majlis.empty": "أنشئ مجلسًا",
        "account.majlis.count": "{n} مجالس",
        "account.majlis.owner": "أنت صاحب «{name}»",
        "account.majlis.cta": "نافس أصدقاءك بكود خاص",
        "account.log.title": "سجل توقعاتي",
        "account.log.empty": "لم تتوقع بعد — ابدأ من تبويب التوقعات",
        "account.log.all": "عرض السجل كاملًا",
        "account.log.myPick": "توقعي: {score}",
        "account.log.miss": "لم يتحقق",
        "account.log.pending": "بالانتظار",
        "account.log.champion": "توقعي للبطل",
        "account.log.topScorer": "هدّاف البطولة",
        "account.fav.title": "منتخبي المفضل",
        "account.fav.set": "منتخبي: {team}",
        "account.fav.subtitle": "مبارياته تتصدر جدول المباريات",
        "account.fav.choose": "اختيار",
        "account.fav.change": "تغيير",
        "account.fav.none": "بدون تفضيل",
        "account.tools.title": "أدوات",
        "account.tools.widget": "ويدجت الشاشة الرئيسية",
        "account.tools.widget.sub": "مباراة اليوم وترتيب المجموعة على شاشتك",
        "account.tools.card": "بطاقة إنجازي",
        "account.tools.card.sub": "صورة جاهزة للمشاركة بنقاطي وترتيبي",
        "account.card.tagline": "متوقّع في مسابقة خليجي 27",
        "account.card.streak": "سلسلة",
        "account.card.footer": "توقّع ونافس — تطبيق خليجي 27 من سبق",
        "account.widget.title": "أضف الويدجت لشاشتك",
        "account.widget.step1": "اضغط مطوّلًا على مساحة فارغة في الشاشة الرئيسية",
        "account.widget.step2": "اختر زر الإضافة (+) أعلى الشاشة ثم ابحث عن «خليجي 27»",
        "account.widget.step3": "اختر الحجم المناسب واضغط «إضافة الويدجت»",
        "account.widget.live": "أثناء المباريات المباشرة ستظهر النتيجة لحظة بلحظة في الأنشطة الحية على شاشة القفل وDynamic Island",
        "account.widget.done": "تم",

        // عام
        "refresh.error.title": "تعذّر التحديث",
        "refresh.retry": "إعادة المحاولة",
        "loading.hub": "يتم تجهيز مركز البطولة",
        "loading.matches": "يتم تحديث جدول المباريات",
        "loading.standings": "يتم تحديث الترتيب",
        "loading.predictions": "يتم تحميل مباريات التوقعات",
        "loading.team": "يتم تحميل بيانات المنتخب",
        "loading.scorers": "يتم تحميل لوحة الهدّافين",
        "loading.history": "يتم تحميل سجلّ البطولة",
    ]

    static func text(_ key: String, _ vars: [String: String] = [:]) -> String {
        var s = strings[key] ?? key
        for (k, v) in vars {
            s = s.replacingOccurrences(of: "{\(k)}", with: v)
        }
        return s
    }
}

func L(_ key: String, _ vars: [String: String] = [:]) -> String {
    GcStrings.text(key, vars)
}

func LTeam(_ id: String, fallback: String) -> String { fallback }

func LRound(_ roundEn: String, fallback: String) -> String { fallback.isEmpty ? roundEn : fallback }

func LError(_ error: Error) -> String {
    if let api = error as? APIError { return api.errorDescription ?? "حدث خطأ" }
    return "تعذّر تحميل البيانات"
}
