import Foundation

// نصوص عربية ثابتة لتطبيق خليجي 27 — بدون i18n متعدد اللغات في النسخة الأولى.
enum GcStrings {
    static let strings: [String: String] = [
        "tab.home": "الرئيسية",
        "tab.matches": "المباريات",
        "tab.predictions": "التوقعات",
        "tab.tournament": "البطولة",
        "tab.more": "المزيد",
        "app.title": "خليجي 27",
        "app.host": "السعودية · جدة 2026",
        "brand.by": "من منصة سبق",
        "state.live": "مباشر",
        "state.finished": "انتهت",
        "state.upcoming": "قادمة",
        "time.today": "اليوم",
        "time.tomorrow": "غدًا",

        // الرئيسية
        "home.countdown.title": "العدّ التنازلي للانطلاق",
        "home.today.title": "مباريات اليوم",
        "home.next.title": "أقرب المباريات",
        "home.next.empty.title": "لا مباريات قادمة",
        "home.next.empty.subtitle": "ستُحدَّث عند اقتراب الجولة",
        "home.live.title": "مباشر الآن",
        "home.standings.title": "ترتيب المجموعات",
        "home.scorers.title": "الهدّافون",
        "home.history.title": "سجلّ البطولة",
        "home.history.subtitle": "من 1970 إلى اليوم — 26 نسخة",
        "home.holder": "حامل اللقب",
        "home.mostTitles": "الأكثر تتويجًا",
        "home.venues.title": "ملاعب جدة",
        "hero.badge.special": "كأس الخليج العربي",
        "hero.hostedBy": "تستضيفها السعودية",
        "hero.liveNow": "البطولة منطلقة الآن",
        "countdown.days": "يوم",
        "countdown.hours": "ساعة",
        "countdown.minutes": "دقيقة",
        "countdown.seconds": "ثانية",
        "saudi.title": "الأخضر في خليجي 27",
        "saudi.host": "المستضيف",
        "teams.host.badge": "مضيف",

        // المباريات
        "matches.subtitle": "الجدول الكامل بتوقيت الرياض",
        "matchesHero.matches": "مباراة",
        "matchesHero.finished": "منتهية",
        "metric.team": "منتخب",
        "schedule.title": "جدول المباريات",
        "schedule.empty.title": "لا مباريات",
        "schedule.empty.subtitle": "سيُحدَّث الجدول قريبًا",
        "schedule.round.all": "الكل",
        "schedule.day.all": "كل الأيام",

        // البطولة
        "tournament.subtitle": "المجموعات والأدوار والهدّافون والسجلّ",
        "tournament.seg.groups": "المجموعات",
        "tournament.seg.bracket": "الأدوار",
        "tournament.seg.scorers": "الهدّافون",
        "tournament.seg.history": "السجلّ",
        "standings.section.title": "ترتيب المجموعات",
        "standings.section.subtitle": "يتأهل الأول والثاني من كل مجموعة",
        "standings.qualifyLine": "تأهّل 1–2",
        "standings.col.team": "الفريق",
        "standings.col.points": "نقاط",
        "groups.empty.title": "ستُعلن المجموعات",
        "groups.empty.subtitle": "عقب انطلاق البطولة ستُحدَّث الجداول تلقائيًّا",
        "bracket.title": "الأدوار الإقصائية",
        "bracket.subtitle": "نصف النهائي والنهائي",
        "bracket.semis": "نصف النهائي",
        "bracket.final": "النهائي",
        "bracket.empty.title": "لم تُحدَّد المواجهات بعد",
        "bracket.empty.subtitle": "ستظهر بعد انتهاء دور المجموعات",
        "scorers.title": "هدّافو البطولة",
        "scorers.assists.title": "صنّاع الأهداف",
        "scorers.lastEdition": "أرقام خليجي 26 — بانتظار انطلاق البطولة",
        "scorers.empty.title": "لا أرقام بعد",
        "scorers.empty.subtitle": "تظهر لوحة الهدّافين مع أول أهداف البطولة",
        "scorers.goals": "هدف",
        "scorers.assists": "صناعة",
        "scorers.matches": "مباراة",
        "history.titles.title": "جدول الألقاب",
        "history.editions.title": "كل النسخ",
        "history.titles.unit": "لقب",
        "history.runnerUp.unit": "وصافة",
        "history.hosted.unit": "استضافة",
        "history.champion": "البطل",
        "history.runnerUp": "الوصيف",
        "history.host": "المضيف",
        "history.upcoming": "النسخة القادمة",

        // التوقعات
        "predictions.subtitle": "توقّع وشارك في البركة",
        "predictions.seg.matches": "المباريات",
        "predictions.seg.leaders": "المتصدرون",
        "predictions.seg.long": "البطل والهدّاف",
        "predictions.seg.mine": "سجلّي",
        "predictions.hero.title": "مسابقة التوقعات",
        "predictions.hero.subtitle": "1000 نقطة لكل مباراة تُقسَّم 50/30/20 على النتيجة الدقيقة والفارق والاتجاه",
        "predictions.stat.points": "نقاطي",
        "predictions.stat.exact": "دقيقة",
        "predictions.stat.streak": "سلسلة",
        "predictions.stat.played": "شاركت",
        "predictions.jackpot": "الجائزة المتراكمة",
        "predictions.empty.title": "لا مباريات مفتوحة الآن",
        "predictions.empty.subtitle": "ستظهر مباريات التوقعات عند اقتراب الجولة",
        "predictions.locked": "مغلق",
        "predictions.locked.note": "انتهى وقت التوقّع",
        "predictions.unavailable": "مسابقة التوقعات غير مفعّلة حاليًا",
        "predictions.meta.pool": "البركة",
        "predictions.meta.participant": "مشارك",
        "predictions.meta.prediction": "توقّع",
        "predictions.probs.title": "توقّع النموذج",
        "predictions.crowd.title": "توقّعات الجمهور",
        "predictions.draw": "تعادل",
        "predictions.submit.new": "إرسال التوقّع",
        "predictions.submit.update": "تحديث التوقّع",
        "predictions.submit.saved": "تم الحفظ",
        "predictions.signin.note": "سجّل الدخول بحساب Apple لحفظ توقّعاتك والمنافسة على البركة",
        "predictions.tier.exact": "🎯 النتيجة الدقيقة",
        "predictions.tier.margin": "📏 الفارق الصحيح",
        "predictions.tier.outcome": "✅ الاتجاه الصحيح",
        "predictions.tier.none": "لم تُصِب هذه المرّة",
        "leaderboard.empty.title": "لم يبدأ الترتيب بعد",
        "leaderboard.empty.subtitle": "سيظهر المتصدرون بعد أول جولة توقعات",
        "leaderboard.points": "نقطة",
        "leaderboard.accuracy": "دقّة",
        "long.champion.title": "توقّع بطل خليجي 27",
        "long.champion.subtitle": "بركة 5000 نقطة تُقسَّم على من أصابوا البطل",
        "long.scorer.title": "توقّع هدّاف البطولة",
        "long.scorer.subtitle": "بركة 5000 نقطة — اكتب اسم اللاعب",
        "long.mine": "توقّعك",
        "long.votes": "أكثر الاختيارات",
        "long.locked": "أُغلق باب التوقّع مع انطلاق البطولة",
        "long.scorer.placeholder": "اسم الهدّاف المتوقّع",
        "long.scorer.save": "حفظ توقّع الهدّاف",
        "mine.empty.title": "لا توقّعات بعد",
        "mine.empty.subtitle": "ابدأ بتوقّع أول مباراة مفتوحة",
        "mine.pending": "بانتظار النتيجة",

        // مركز المباراة
        "match.title": "مركز المباراة",
        "match.seg.summary": "ملخّص",
        "match.seg.lineups": "التشكيلات",
        "match.seg.stats": "إحصاءات",
        "match.seg.h2h": "مواجهات",
        "match.events": "أحداث المباراة",
        "match.noEvents.title": "لا أحداث بعد",
        "match.noEvents.subtitle": "يبدأ شريط الأحداث مع صافرة البداية",
        "match.lineups.empty.title": "لم تُعلن التشكيلات",
        "match.lineups.empty.subtitle": "تظهر قبل انطلاق المباراة بنحو ساعة",
        "match.stats.empty.title": "لا إحصاءات بعد",
        "match.stats.empty.subtitle": "تظهر الأرقام مع انطلاق المباراة",
        "match.h2h.record": "الرصيد التاريخي",
        "match.h2h.recent": "آخر المواجهات",
        "match.h2h.tournament": "مواجهات في البطولة",
        "match.h2h.empty.title": "لا سجلّ مواجهات",
        "match.h2h.empty.subtitle": "أول مواجهة بين المنتخبين منذ سنوات",
        "match.wins": "فوز",
        "match.draws": "تعادل",
        "match.coach": "المدرّب",
        "match.formation": "الخطّة",
        "match.startXI": "التشكيلة الأساسية",
        "match.subs": "البدلاء",
        "match.info.venue": "الملعب",
        "match.info.date": "التاريخ",
        "match.info.time": "الوقت",
        "match.info.matchNo": "رقم المباراة",
        "match.loading": "يتم تحميل تفاصيل المباراة",
        "liveActivity.start": "متابعة على شاشة القفل",
        "liveActivity.stop": "إيقاف المتابعة",

        // المنتخب
        "team.subtitle.group": "في {group}",
        "team.nextMatch": "المباراة القادمة",
        "team.fixtures": "جدول المنتخب",
        "team.group": "مجموعته",
        "team.squad": "قائمة المنتخب",
        "team.form": "آخر النتائج",
        "team.legacy.title": "الإرث الخليجي",
        "team.legacy.years": "سنوات التتويج",
        "team.coach": "المدرّب",
        "team.squad.empty.title": "لم تُعلن القائمة",
        "team.squad.empty.subtitle": "تظهر قائمة اللاعبين فور اعتمادها",
        "position.Goalkeeper": "حراسة المرمى",
        "position.Defender": "الدفاع",
        "position.Midfielder": "الوسط",
        "position.Attacker": "الهجوم",
        "stats.played": "لعب",
        "stats.points": "نقاط",
        "stats.diff": "فارق",
        "stats.win": "فوز",
        "stats.draw": "تعادل",
        "stats.lose": "خسارة",
        "stats.goalsFor": "له",
        "stats.goalsAgainst": "عليه",

        // المزيد
        "more.subtitle": "المنتخبات والملاعب والحساب",
        "more.about.title": "عن البطولة",
        "more.about.body": "النسخة 27 من كأس الخليج العربي — تستضيفها السعودية في جدة من 23 سبتمبر إلى 6 أكتوبر 2026، بمشاركة 8 منتخبات على ملعبَي مدينة الملك عبدالله الرياضية والأمير عبدالله الفيصل.",
        "teams.section.title": "منتخبات البطولة",
        "teams.empty.title": "ستظهر المنتخبات",
        "teams.empty.subtitle": "فور تحميل بيانات البطولة",
        "venues.section.title": "ملاعب الاستضافة",
        "account.title": "حسابي",
        "account.subtitle": "لحفظ التوقعات والمشاركة في البركة",
        "account.signout": "خروج",
        "account.member.fallback": "عضو سبق",
        "account.signedIn": "مسجّل الدخول",
        "account.signin.note": "سجّل الدخول بحساب Apple لحفظ توقّعاتك في مسابقة خليجي 27",

        // عام
        "refresh.error.title": "تعذّر التحديث",
        "refresh.retry": "إعادة المحاولة",
        "loading.hub": "يتم تجهيز مركز البطولة",
        "loading.matches": "يتم تحديث جدول المباريات",
        "loading.standings": "يتم تحديث الترتيب",
        "loading.predictions": "يتم تحميل مباريات التوقعات",
        "loading.team": "يتم تحميل بيانات المنتخب",
        "loading.scorers": "يتم تحميل لوحة الهدّافين",
        "loading.history": "يتم تحميل سجلّ البطولة",
    ]

    static func text(_ key: String, _ vars: [String: String] = [:]) -> String {
        var s = strings[key] ?? key
        for (k, v) in vars {
            s = s.replacingOccurrences(of: "{\(k)}", with: v)
        }
        return s
    }
}

func L(_ key: String, _ vars: [String: String] = [:]) -> String {
    GcStrings.text(key, vars)
}

func LTeam(_ id: String, fallback: String) -> String { fallback }

func LRound(_ roundEn: String, fallback: String) -> String { fallback.isEmpty ? roundEn : fallback }

func LError(_ error: Error) -> String {
    if let api = error as? APIError { return api.errorDescription ?? "حدث خطأ" }
    return "تعذّر تحميل البيانات"
}
