/** أسماء عربية نظيفة لصفوف تقرير نقاط البيع — مفتاحها الاسم الإنجليزي كما يطبعه PDF ساما.
 * نص PDF العربي يصل بأشكال عرض مكسورة (األ/اإل)، فالاسم الإنجليزي هو المفتاح الثابت. */
export const POS_ACTIVITY_AR: Record<string, string> = {
  "Transportation": "النقل",
  "Airlines": "الطيران",
  "Auto & Equipment Rentals": "تأجير السيارات والمعدات",
  "Trade of Vehicles & Spare Parts": "تجارة المركبات وقطع الغيار",
  "Maintenance & Repair of Vehicles": "صيانة وإصلاح المركبات",
  "Freight Transport & Postal & Courier Services": "خدمات الشحن والتوصيل ونقل الطرود",
  "Others": "أخرى",
  "Health": "الصحة",
  "Medical Services": "الخدمات الطبية",
  "Pharmacies & Medical Supplies": "الصيدليات والمستلزمات الطبية",
  "Personal Care": "العناية الشخصية",
  "Restaurants & Cafés": "المطاعم والمقاهي",
  "Bakeries & Pastries": "المخبوزات والحلويات",
  "Hotels": "الفنادق",
  "Food & Beverages": "الأطعمة والمشروبات",
  "Apparel, Clothing & Accessories": "الملبوسات والإكسسوارات",
  "Recreation & Culture": "الثقافة والترفيه",
  "Books & Stationery": "الكتب والأدوات المكتبية",
  "Recreation": "الترفيه",
  "Professional & Business Services": "الخدمات المهنية والتجارية",
  "Electronic & Electric Devices": "الأجهزة الإلكترونية والكهربائية",
  "Furniture & Home Supplies": "الأثاث والمستلزمات المنزلية",
  "Construction & Building Materials": "مواد البناء والتعمير",
  "Jewelry": "المجوهرات",
  "Telecommunication": "الاتصالات",
  "Education": "التعليم",
  "Public Utilities & Services": "المنافع والخدمات العامة",
  "Gas Stations": "محطات الوقود",
  "Laundry Services": "خدمات غسيل الملابس",
  "Total": "الإجمالي"
};

export const POS_CITY_AR: Record<string, string> = {
  "Abha": "أبها",
  "Abu-Areesh": "أبو عريش",
  "Ahad-Almasarha": "أحد المسارحة",
  "Ahad-Rufaidah": "أحد رفيدة",
  "Al-Baha": "الباحة",
  "Al-Badaea": "البدائع",
  "Al-Bekairiyah": "البكيرية",
  "Al-Jubail": "الجبيل",
  "Al-Khubar": "الخبر",
  "Al-Kharj": "الخرج",
  "Al-Khafji": "الخفجي",
  "Al-Darb": "الدرب",
  "Dammam": "الدمام",
  "Al-Dawadmi": "الدوادمي",
  "Al-Rass": "الرس",
  "Riyadh": "الرياض",
  "Al-Zulfi": "الزلفي",
  "Al-Tayef": "الطائف",
  "Al-Dahran": "الظهران",
  "Al-Ola": "العلا",
  "Al-Qurayyat": "القريات",
  "Al-Qateef": "القطيف",
  "Al-Gunfudah": "القنفذة",
  "Al-Queyah": "القويعية",
  "Al-laith": "الليث",
  "Al-Mubarraz": "المبرز",
  "Al-Majma'a": "المجمعة",
  "Al-Madinah": "المدينة المنورة",
  "Al-Muzahmiya": "المزاحمية",
  "Al-Neairiyah": "النعيرية",
  "Al-Hofuf": "الهفوف",
  "Amluj": "أملج",
  "Buraidah": "بريدة",
  "Baish": "بيش",
  "Besha": "بيشة",
  "Tabouk": "تبوك",
  "Jazan": "جازان",
  "Jeddah": "جدة",
  "Hayel": "حائل",
  "Hafrel-Batin": "حفر الباطن",
  "Khamis-Mushait": "خميس مشيط",
  "Rabehg": "رابغ",
  "Rafha": "رفحاء",
  "Sakaka": "سكاكا",
  "Saihat": "سيهات",
  "Sharora": "شرورة",
  "Shagraa": "شقراء",
  "Samta": "صامطة",
  "Sabya": "صبيا",
  "Safwa": "صفوى",
  "Tabarjal": "طبرجل",
  "Tareef": "طريف",
  "Ar'ar": "عرعر",
  "Afeef": "عفيف",
  "Onaizah": "عنيزة",
  "Mahayel": "محايل",
  "Makkah": "مكة المكرمة",
  "Najran": "نجران",
  "Wadil-Dawaser": "وادي الدواسر",
  "Yanbu": "ينبع",
  "Others": "أخرى"
};
